from amocrm.v2 import Contact as _Contact
from amocrm.v2 import Company as _Company
from amocrm.v2 import Lead as _Lead
from amocrm.v2 import tokens, custom_field


class Contact(_Contact):
    dolzhnost = custom_field.TextCustomField("Должность", field_id=1026764, code="POSITION")
    telefon = custom_field.ContactPhoneField("Телефон", field_id=1026766, code="PHONE")
    email = custom_field.ContactEmailField("Email", field_id=1026768, code="EMAIL")
    mgn_soobshcdeniia = custom_field.BaseCustomField("Мгн. сообщения", field_id=1026772, code="IM")
    polzovatelskoe_soglashenie = custom_field.CheckboxCustomField("Пользовательское соглашение", field_id=1299072, code="USER_AGREEMENT")
    mailchimp = custom_field.CheckboxCustomField("MailChimp", field_id=1299786)
    nomer_dogovora = custom_field.TextCustomField("Номер договора", field_id=1301850)

    class OTVETSTVENNYI_MENEDZHER_ENUMS:
        zhakov = custom_field.SelectValue(id=2990554, value='Жаков')
        garbul = custom_field.SelectValue(id=2990556, value='Гарбуль')
        sagalov = custom_field.SelectValue(id=2990558, value='Сагалов')
        ivanov = custom_field.SelectValue(id=2990560, value='Иванов')
        bragin = custom_field.SelectValue(id=2990562, value='Брагин')
        solovev = custom_field.SelectValue(id=2995570, value='Соловьев')
    otvetstvennyi_menedzher = custom_field.SelectCustomField("Ответственный менеджер", field_id=1301852, enums=OTVETSTVENNYI_MENEDZHER_ENUMS)
    source_phone = custom_field.TextCustomField("Source phone", field_id=1304816)
    status_kontakta = custom_field.TextCustomField("Статус контакта", field_id=1469944)
    telegramusername_wz = custom_field.TextCustomField("TelegramUsername_WZ", field_id=1470468)
    telegramid_wz = custom_field.TextCustomField("TelegramId_WZ", field_id=1470470)


class Company(_Company):
    telefon = custom_field.ContactPhoneField("Телефон", field_id=1026766, code="PHONE")
    email = custom_field.ContactEmailField("Email", field_id=1026768, code="EMAIL")
    web = custom_field.UrlCustomField("Web", field_id=1026770, code="WEB")
    adres = custom_field.TextAreaCustomField("Адрес", field_id=1026774, code="ADDRESS")


class Lead(_Lead):

    class OTKUDA_SREDSTVA_ENUMS:
        sobstvennye_sredstva = custom_field.SelectValue(id=2932553, value='Собственные средства')
        sobstvennye_sredstva = custom_field.SelectValue(id=2932555, value='Собственные средства / кредит')
        subsidii = custom_field.SelectValue(id=2932557, value='Субсидии')
        otkazalsia_otvechat = custom_field.SelectValue(id=2932559, value='Отказался отвечать')
        kredit = custom_field.SelectValue(id=2942465, value='Кредит')
        sredstva_partnera = custom_field.SelectValue(id=2942543, value='Средства партнера')
    otkuda_sredstva = custom_field.SelectCustomField("Откуда средства", field_id=1275415, enums=OTKUDA_SREDSTVA_ENUMS)

    class TIP_TRAFFIKA_ENUMS:
        iandeks_direkt = custom_field.SelectValue(id=2932577, value='Яндекс Директ')
        google_adwords = custom_field.SelectValue(id=2932579, value='Google Adwords')
        beboss = custom_field.SelectValue(id=2932581, value='Beboss')
        franch_biz = custom_field.SelectValue(id=2932583, value='Franch.biz')
        franshiza_ru = custom_field.SelectValue(id=2932585, value='Franshiza.ru')
        kupifranshizu_ru = custom_field.SelectValue(id=2932587, value='Kupifranshizu.ru')
        pr_forbes_dp = custom_field.SelectValue(id=2932589, value='PR (Forbes, ДП и т.д.)')
        reshanov_com = custom_field.SelectValue(id=2932591, value='Reshanov.com')
        drugie_portaly = custom_field.SelectValue(id=2932593, value='Другие порталы')
        drugoi_variant = custom_field.SelectValue(id=2932597, value='Другой вариант')
        lichnoe_znakomstvo = custom_field.SelectValue(id=2932599, value='Личное знакомство')
        meropriiatiia = custom_field.SelectValue(id=2932601, value='Мероприятия')
        doski = custom_field.SelectValue(id=2942071, value='Доски')
        avito = custom_field.SelectValue(id=2942073, value='Авито')
        profranch_com = custom_field.SelectValue(id=2943431, value='profranch.com')
        megamagnat_ru = custom_field.SelectValue(id=2943433, value='megamagnat.ru')
        biztorg_ru = custom_field.SelectValue(id=2943435, value='biztorg.ru')
        sellbrand_ru = custom_field.SelectValue(id=2943437, value='sellbrand.ru')
        getbiz_ru = custom_field.SelectValue(id=2943439, value='getbiz.ru')
        topfranchise_ru = custom_field.SelectValue(id=2943443, value='topfranchise.ru')
        bportal_ru = custom_field.SelectValue(id=2943445, value='bportal.ru')
        buybrand_ru = custom_field.SelectValue(id=2943447, value='buybrand.ru')
        profranshizu_ru = custom_field.SelectValue(id=2943449, value='profranshizu.ru')
        franshizy_com = custom_field.SelectValue(id=2943451, value='franshizy.com')
        openbusiness_ru = custom_field.SelectValue(id=2943453, value='openbusiness.ru')
        businessesforsale_ru = custom_field.SelectValue(id=2943455, value='businessesforsale.ru')
        target_vk = custom_field.SelectValue(id=2953966, value='таргет VK')
        target_fb = custom_field.SelectValue(id=2953980, value='таргет FB')
        target_ok = custom_field.SelectValue(id=2954216, value='таргет OK')
        one = custom_field.SelectValue(id=2954382, value='1')
        two = custom_field.SelectValue(id=2954384, value='2')
        organika = custom_field.SelectValue(id=2954386, value='Органика')
        youtube = custom_field.SelectValue(id=2954388, value='YouTube')
        email_rassylka = custom_field.SelectValue(id=2954390, value='Email рассылка')
        getresponce = custom_field.SelectValue(id=2954510, value='getresponce')
        three = custom_field.SelectValue(id=2954652, value='3')
        chernaia_piatnitsa = custom_field.SelectValue(id=2954708, value='Черная Пятница')
        franshiza_info = custom_field.SelectValue(id=2954894, value='franshiza-info')
        bizoomie = custom_field.SelectValue(id=2955038, value='bizoomie')
        money_maker_factory = custom_field.SelectValue(id=2956080, value='Money Maker Factory')
        businesspartner_ru = custom_field.SelectValue(id=2956158, value='businesspartner.ru')
        bzzone_ru = custom_field.SelectValue(id=2956285, value='BzZone.ru')
        franchise_ua = custom_field.SelectValue(id=2956598, value='Franchise.ua')
        russtartup = custom_field.SelectValue(id=2956714, value='russtartup')
        businessmens = custom_field.SelectValue(id=2956716, value='businessmens')
        timesnet = custom_field.SelectValue(id=2956718, value='timesnet')
        moneybrain = custom_field.SelectValue(id=2956720, value='moneybrain')
        uspehfouru = custom_field.SelectValue(id=2956722, value='uspeh4u')
        delatdelo = custom_field.SelectValue(id=2956726, value='delatdelo')
        delu_vremia = custom_field.SelectValue(id=2956950, value='Делу время')
        b_p_dlia_predprinimatelei = custom_field.SelectValue(id=2957012, value='Б-П для предпринимателей')
        iz_ruk_v = custom_field.SelectValue(id=2957120, value='из рук в руки')
        franchay_ru = custom_field.SelectValue(id=2958257, value='franchay.ru')
        biznestaim = custom_field.SelectValue(id=2958296, value='бизнестайм')
        franchobzor = custom_field.SelectValue(id=2958326, value='franchobzor')
        kakzarabativat = custom_field.SelectValue(id=2958529, value='kakzarabativat')
        shopandmall = custom_field.SelectValue(id=2958531, value='shopandmall')
        franshiza_top_ru = custom_field.SelectValue(id=2958738, value='franshiza-top.ru')
        bm = custom_field.SelectValue(id=2959004, value='БМ')
        business_asset_exchange = custom_field.SelectValue(id=2959080, value='Business Asset Exchange')
        zvonok_po_bazam = custom_field.SelectValue(id=2959776, value='Звонок по базам')
        onlain_konsultant = custom_field.SelectValue(id=2963552, value='Онлайн консультант')
        bisnesideya_ru = custom_field.SelectValue(id=2963572, value='bisnesideya.ru')
        biznes_prost_ru = custom_field.SelectValue(id=2963582, value='Biznes-Prost.ru')
        belfranchaizing = custom_field.SelectValue(id=2964899, value='Белфранчайзинг')
        zaiavka_s_investitsii = custom_field.SelectValue(id=2965248, value='Заявка с инвестиций')
        btwob_context = custom_field.SelectValue(id=2965266, value='B2B Context')
        franshizas_ru = custom_field.SelectValue(id=2965625, value='franshizas.ru')
        ktovdele = custom_field.SelectValue(id=2965983, value='ktovdele')
        palatapredprkakhastan = custom_field.SelectValue(id=2966066, value='ПалатаПредпрКахастан')
        uznal_ot_konkurentov = custom_field.SelectValue(id=2966370, value='Узнал от конкурентов')
        equipnet_ru = custom_field.SelectValue(id=2966420, value='equipnet.ru')
        idei_dela = custom_field.SelectValue(id=2966791, value='идеи-дела')
        bebossone = custom_field.SelectValue(id=2967045, value='Beboss1')
        bebosstwo = custom_field.SelectValue(id=2967047, value='Beboss2')
        bebossthree = custom_field.SelectValue(id=2967049, value='Beboss3')
        bebossfour = custom_field.SelectValue(id=2967051, value='Beboss4')
        bebossfive = custom_field.SelectValue(id=2967053, value='Beboss5')
        bebosssix = custom_field.SelectValue(id=2967055, value='Beboss6')
        bebossseven = custom_field.SelectValue(id=2967057, value='Beboss7')
        bebosseight = custom_field.SelectValue(id=2967059, value='Beboss8')
        hiterbober = custom_field.SelectValue(id=2967131, value='hiterbober')
        bebossnine = custom_field.SelectValue(id=2967251, value='Beboss9')
        bebossonezero = custom_field.SelectValue(id=2967271, value='Beboss10')
        business_poisk_com = custom_field.SelectValue(id=2967345, value='business-poisk.com')
        vk_posty = custom_field.SelectValue(id=2969547, value='VK посты')
        dengi_ledi = custom_field.SelectValue(id=2970411, value='Деньги-леди')
        dengodel = custom_field.SelectValue(id=2970471, value='Деньгодел')
        bizreiting = custom_field.SelectValue(id=2970473, value='Бизрейтинг')
        pro_biznes = custom_field.SelectValue(id=2970475, value='PRO-БИЗНЕС')
        biznesvbloge_ru = custom_field.SelectValue(id=2970715, value='biznesvbloge.ru')
        abcbiznes_ru = custom_field.SelectValue(id=2970717, value='abcbiznes.ru')
        greens_idea_com = custom_field.SelectValue(id=2970719, value='greens-idea.com')
        biznes_prost_malyi = custom_field.SelectValue(id=2970721, value='Бизнес-прост (малый)')
        tekushchii_partner = custom_field.SelectValue(id=2972169, value='Текущий партнер')
        broker_nikolai_bereza = custom_field.SelectValue(id=2972442, value='Брокер Николай Береза')
        homebusiness_ru = custom_field.SelectValue(id=2973284, value='homebusiness.ru')
        vygodnyi_vklad_rf = custom_field.SelectValue(id=2973286, value='выгодный-вклад. рф')
        melnicabiz_ru = custom_field.SelectValue(id=2974192, value='melnicabiz.ru')
        znaydelo_ru = custom_field.SelectValue(id=2975382, value='znaydelo.ru')
        vk_eva = custom_field.SelectValue(id=2975402, value='VK Ева')
        club_franshiz = custom_field.SelectValue(id=2975414, value='club-franshiz')
        bisplatform = custom_field.SelectValue(id=2975796, value='bisplatform')
        vk_gruppa = custom_field.SelectValue(id=2975820, value='VK группа')
        to_biz_ru = custom_field.SelectValue(id=2976144, value='to-biz.ru')
        biz_anatomy_ru = custom_field.SelectValue(id=2979516, value='biz-anatomy.ru')
        www_businesstrade_by = custom_field.SelectValue(id=2982268, value='www.businesstrade.by')
        tilda_sezd_partniorov = custom_field.SelectValue(id=2984228, value='Тильда Съезд партнёров')
        yastaff = custom_field.SelectValue(id=2984534, value='yastaff')
        neizvestno = custom_field.SelectValue(id=2984536, value='неизвестно')
        zachestnyibiznes = custom_field.SelectValue(id=2985272, value='zachestnyibiznes')
        denis_oneseven_iiulia = custom_field.SelectValue(id=2986902, value='Денис 17 июля')
        deloshop = custom_field.SelectValue(id=2987384, value='deloshop')
        reklama_socmedia = custom_field.SelectValue(id=2987478, value='Реклама SocMedia')
        myfranch = custom_field.SelectValue(id=2987516, value='myfranch')
        sdengami_ru = custom_field.SelectValue(id=2989068, value='sdengami.ru')
        franchise_otzyv_ru = custom_field.SelectValue(id=2989070, value='franchise-otzyv.ru')
        smi = custom_field.SelectValue(id=2989794, value='СМИ')
        vsefranshizi_ru = custom_field.SelectValue(id=2990184, value='vsefranshizi.ru')
        alterainvest = custom_field.SelectValue(id=2991214, value='АльтераИнвест')
        bizbank = custom_field.SelectValue(id=2991436, value='bizbank')
        gruppa_bestidea = custom_field.SelectValue(id=2991474, value='Группа Bestidea')
        gruppa_idei_biznesa = custom_field.SelectValue(id=2991476, value='Группа Идеи Бизнеса')
        realybiz = custom_field.SelectValue(id=2992022, value='realybiz')
        actual_biznes_idei = custom_field.SelectValue(id=2992032, value='Actual Бизнес идеи VK')
        malyi_biznes_vk = custom_field.SelectValue(id=2992034, value='Малый бизнес VK')
        svoi_biznes_vk = custom_field.SelectValue(id=2992036, value='Свой БИЗНЕС VK')
        katalog_biznes_idei = custom_field.SelectValue(id=2992038, value='Каталог бизнес идей VK')
        biznet = custom_field.SelectValue(id=2992082, value='biznet')
        ideibiznesa_org = custom_field.SelectValue(id=2992102, value='ideibiznesa.org')
        instagram_denisa = custom_field.SelectValue(id=2992364, value='Instagram Denisa')
        telegram_denisa = custom_field.SelectValue(id=2992366, value='Telegram Denisa')
        fr_mall = custom_field.SelectValue(id=2996844, value='FR.Mall')
        aktsiia_shattly = custom_field.SelectValue(id=2996984, value='Акция шаттлы')
        biznesplan_primer_ru = custom_field.SelectValue(id=2997750, value='biznesplan-primer.ru')
        didzhital_baff = custom_field.SelectValue(id=2997950, value='Диджитал Бафф')
        mutnyi_kholod = custom_field.SelectValue(id=2998358, value='Мутный холод')
        want_result = custom_field.SelectValue(id=2998360, value='Want Result')
        fpshop = custom_field.SelectValue(id=2998874, value='FPshop')
        katalog_franshiz_vk = custom_field.SelectValue(id=2999136, value='Каталог Франшиз VK')
        didzhital_baff_chatbot = custom_field.SelectValue(id=2999304, value='Диджитал Бафф Чатбот')
        newbusiness_su = custom_field.SelectValue(id=2999558, value='newbusiness.su')
        avtovoronka = custom_field.SelectValue(id=2999714, value='Автоворонка')
        onezerozerozero_ideas = custom_field.SelectValue(id=3000422, value='1000 ideas')
        pride_mail_target = custom_field.SelectValue(id=3000708, value='Pride Mail Target')
        helpfranchise_ru = custom_field.SelectValue(id=3001490, value='helpfranchise.ru')
        akademyey = custom_field.SelectValue(id=3003492, value='AkademyEY')
        sberbank_franshizy = custom_field.SelectValue(id=3004216, value='Сбербанк Франшизы')
        fbm_ru = custom_field.SelectValue(id=3004260, value='fbm.ru')
        http_myrouble_ru = custom_field.SelectValue(id=3004262, value='http://myrouble.ru/')
        sverdlovskii_fond = custom_field.SelectValue(id=3004362, value='Свердловский фонд')
        franchbook = custom_field.SelectValue(id=3006772, value='franchbook')
        sabit = custom_field.SelectValue(id=3007068, value='Sabit')
        led_digital = custom_field.SelectValue(id=3007078, value='Led-digital')
        delosmelo_ru = custom_field.SelectValue(id=3007656, value='delosmelo.ru')
        biznesknigi = custom_field.SelectValue(id=3007918, value='biznesknigi')
        biznesideas = custom_field.SelectValue(id=3008102, value='biznesideas')
        iula = custom_field.SelectValue(id=3008570, value='Юла')
        instfranshima = custom_field.SelectValue(id=3009016, value='instFranshima')
        igor_mann = custom_field.SelectValue(id=3009412, value='Игорь Манн')
        adne_info = custom_field.SelectValue(id=3009536, value='adne-info')
        whatsapp = custom_field.SelectValue(id=3009836, value='WhatsApp')
        spark = custom_field.SelectValue(id=3009838, value='Spark')
        franch_city = custom_field.SelectValue(id=3010090, value='franch-city')
        staroverov_pr = custom_field.SelectValue(id=3010176, value='Староверов ПР')
        arkstiks = custom_field.SelectValue(id=3010818, value='Аркстикс')
        digital_buff = custom_field.SelectValue(id=3010844, value='Digital.buff')
        biznes_ru = custom_field.SelectValue(id=3011820, value='Бизнес.ру')
        partnerkin = custom_field.SelectValue(id=3012146, value='Партнеркин')
        oldboi = custom_field.SelectValue(id=3012148, value='Олдбой')
        pedant = custom_field.SelectValue(id=3012150, value='Педант')
        telegram_kanaly = custom_field.SelectValue(id=3012170, value='Телеграм-каналы')
        target_ann = custom_field.SelectValue(id=3012200, value='Target_Ann')
        insta_eva = custom_field.SelectValue(id=3012214, value='insta_eva')
        tg_posevi = custom_field.SelectValue(id=3012286, value='TG_posevi')
        vk_posevi = custom_field.SelectValue(id=3012288, value='VK_posevi')
        instagram_blogery = custom_field.SelectValue(id=3012306, value='Инстаграм-блогеры')
        dzen_posevi = custom_field.SelectValue(id=3012558, value='dzen_posevi')
        dominos = custom_field.SelectValue(id=3012576, value='dominos')
        tg_bot = custom_field.SelectValue(id=3012616, value='TG_bot')
        insta_story = custom_field.SelectValue(id=3012766, value='Insta_story')
        aktsii = custom_field.SelectValue(id=3012782, value='Акции')
        invest = custom_field.SelectValue(id=3012792, value='Invest')
        paket_agent = custom_field.SelectValue(id=3013004, value='Пакет агент')
        youtube_posevi = custom_field.SelectValue(id=3013012, value='youtube_posevi')
        aglamov = custom_field.SelectValue(id=3013016, value='Aglamov')
        baza_lazerlav = custom_field.SelectValue(id=3013266, value='База Лазерлав')
        kiberone = custom_field.SelectValue(id=3013507, value='KiberOne')
        baza_avito_parcer = custom_field.SelectValue(id=3013588, value='База_Avito_parcer')
        offer_zakrytye = custom_field.SelectValue(id=3013602, value='Оффер_закрытые')
        samozaniatye_rf = custom_field.SelectValue(id=3013674, value='самозанятые.рф')
        abdm = custom_field.SelectValue(id=3013696, value='ABDM')
        vk_fr_yastaff = custom_field.SelectValue(id=3014956, value='ВК fr.yastaff')
        aglamov_ia_direkt = custom_field.SelectValue(id=3015068, value='Aglamov Я.Директ')
        baza_bobiormaster = custom_field.SelectValue(id=3015080, value='База_БобёрМастер')
        baza_khimchistki = custom_field.SelectValue(id=3015084, value='База_Химчистки')
        vk_senler = custom_field.SelectValue(id=3015100, value='VK_senler')
        starye_bazy = custom_field.SelectValue(id=3015118, value='Старые базы')
        tg_kanal_gk = custom_field.SelectValue(id=3015148, value='TG_kanal_GK')
        zvooc_target = custom_field.SelectValue(id=3015152, value='Zvooc_target')
        vc_promo = custom_field.SelectValue(id=3015274, value='VC_promo')
        markway_otzyvy = custom_field.SelectValue(id=3015424, value='Markway_Отзывы')
        transformator = custom_field.SelectValue(id=3015440, value='Трансформатор')
        prozvon_franchbook = custom_field.SelectValue(id=3015464, value='Прозвон franchbook')
        dzen_target = custom_field.SelectValue(id=3015470, value='Дзен.Таргет')
        vebinar = custom_field.SelectValue(id=3015532, value='Вебинар')
        wa = custom_field.SelectValue(id=3015834, value='WA')
        yandex_rustem = custom_field.SelectValue(id=3015854, value='yandex_Rustem')
        ima_biznes = custom_field.SelectValue(id=3015874, value='ima_Бизнес')
        tg_kanal_gk = custom_field.SelectValue(id=3015878, value='tg_kanal_gk')
        seriakov_investitsii = custom_field.SelectValue(id=3015922, value='Серяков инвестиции')
        head_hunter = custom_field.SelectValue(id=3016066, value='Head Hunter')
        agent_fr_prozvon = custom_field.SelectValue(id=3016128, value='Агент Фр Прозвон')
        zvooc_prozvon = custom_field.SelectValue(id=3016190, value='zvooc_прозвон')
    tip_traffika = custom_field.SelectCustomField("Тип траффика", field_id=1275417, enums=TIP_TRAFFIKA_ENUMS)

    class VLOZHENIIA_ENUMS:
        twozerozero_threezerozero_t_r = custom_field.SelectValue(id=2932967, value='200-300 т.р.')
        do_onezerozero_t_r = custom_field.SelectValue(id=2932969, value='до 100 т.р.')
        onezerozero_twozerozero_t_r = custom_field.SelectValue(id=2932973, value='100-200 т.р.')
        threezerozero_fourzerozero_t_r = custom_field.SelectValue(id=2944834, value='300-400 т.р.')
        fourzerozero_fivezerozero_t_r = custom_field.SelectValue(id=2944836, value='400-500 т.р.')
        fivezerozero_sixzerozero_t_r = custom_field.SelectValue(id=2944838, value='500-600 т.р.')
        ot_sixzerozero_t_r = custom_field.SelectValue(id=2944844, value='от 600 т.р.')
        otkazalsia_otvechat = custom_field.SelectValue(id=2997208, value='Отказался отвечать')
    vlozheniia = custom_field.SelectCustomField("Вложения", field_id=1275419, enums=VLOZHENIIA_ENUMS)
    data_prikhoda_obrashcheniia = custom_field.DateCustomField("Дата прихода обращения", field_id=1275421)

    class SROKI_STARTA_ENUMS:
        v_techenie_mesiatsa = custom_field.SelectValue(id=2932605, value='В течение месяца')
        ot_mesiatsa_do = custom_field.SelectValue(id=2932607, value='От месяца до 3-х')
        ot_three_kh_do = custom_field.SelectValue(id=2932609, value='От 3-х до 6-ти')
        bolee_six_ti = custom_field.SelectValue(id=2932611, value='Более 6-ти')
        otkazalsia_otvechat = custom_field.SelectValue(id=2997210, value='Отказался отвечать')
    sroki_starta = custom_field.SelectCustomField("Сроки старта", field_id=1275425, enums=SROKI_STARTA_ENUMS)

    class RASSMATRIVAET_VARIANTY_ENUMS:
        tolko_nas = custom_field.SelectValue(id=2954238, value='только нас')
        ne_tolko_nas = custom_field.SelectValue(id=2954240, value='не только нас')
        priamykh_konkurentov = custom_field.SelectValue(id=2978100, value='прямых конкурентов')
    rassmatrivaet_varianty = custom_field.SelectCustomField("Рассматривает варианты", field_id=1275429, enums=RASSMATRIVAET_VARIANTY_ENUMS)

    class TIP_ENUMS:
        molodezh = custom_field.SelectValue(id=2932623, value='Молодежь')
        predprinimatel_smezhnik = custom_field.SelectValue(id=2932625, value='Предприниматель - смежник')
        predprinimatel_kollegi = custom_field.SelectValue(id=2932627, value='Предприниматель - коллеги')
        potolochnik = custom_field.SelectValue(id=2985748, value='Потолочник')
        predprinimatel_vtoraia = custom_field.SelectValue(id=2997200, value='Предприниматель - вторая попытка')
        organizatsiia = custom_field.SelectValue(id=2997202, value='Организация')
        investor = custom_field.SelectValue(id=2997204, value='Инвестор')
        otkazalsia_otvechat = custom_field.SelectValue(id=2997206, value='Отказался отвечать')
    tip = custom_field.SelectCustomField("Тип", field_id=1275431, enums=TIP_ENUMS)

    class OZHIDANIIA_PO_PRIBYLI_ENUMS:
        onezerozero_t_r = custom_field.SelectValue(id=2954220, value='100 т.р.')
        onefivezero_t_r = custom_field.SelectValue(id=2954222, value='150 т.р.')
        twozerozero_t_r = custom_field.SelectValue(id=2954224, value='200 т.р.')
        twofivezero_t_r = custom_field.SelectValue(id=2954226, value='250 т.р.')
        bolee_twofivezero_t_r = custom_field.SelectValue(id=2954228, value='более 250 т.р.')
        do_onezerozero_t_r = custom_field.SelectValue(id=2954696, value='до 100 т.р.')
    ozhidaniia_po_pribyli = custom_field.SelectCustomField("Ожидания (по прибыли)", field_id=1275433, enums=OZHIDANIIA_PO_PRIBYLI_ENUMS)

    class PAKET_ENUMS:
        startap = custom_field.SelectValue(id=2932631, value='Стартап')
        predprinimatel = custom_field.SelectValue(id=2932633, value='Предприниматель')
        gotovyi_biznes = custom_field.SelectValue(id=2932635, value='Готовый бизнес')
        ekskliuziv = custom_field.SelectValue(id=2932637, value='Эксклюзив')
        investor = custom_field.SelectValue(id=2932639, value='Инвестор')
        sneg = custom_field.SelectValue(id=2955504, value='Снег')
        biznes_plan = custom_field.SelectValue(id=2966376, value='Бизнес-план')
        brend = custom_field.SelectValue(id=3010178, value='Бренд')
        agent = custom_field.SelectValue(id=3012988, value='Агент')
        kursn = custom_field.SelectValue(id=3015168, value='КурсН')
        kurso = custom_field.SelectValue(id=3015170, value='КурсО')
    paket = custom_field.SelectCustomField("Пакет", field_id=1275435, enums=PAKET_ENUMS)
    utm_source = custom_field.TextCustomField("utm_source", field_id=1277323)
    utm_medium = custom_field.TextCustomField("utm_medium", field_id=1277325)
    utm_campaign = custom_field.TextCustomField("utm_campaign", field_id=1277327)
    utm_term = custom_field.TextCustomField("utm_term", field_id=1277329)
    ga_utm = custom_field.TextCustomField("GA UTM", field_id=1277331)

    class PRICHINA_OTKOLA_OLD_ENUMS:
        ne_otvechaet_sbrasyvaet = custom_field.SelectValue(id=2939743, value='Не отвечает/сбрасывает')
        net_deneg = custom_field.SelectValue(id=2939747, value='Нет денег')
        stolknulsia_s_negativom = custom_field.SelectValue(id=2939749, value='Столкнулся с негативом от партнеров')
        prochee = custom_field.SelectValue(id=2945196, value='Прочее')
        sroki_bolshie_na = custom_field.SelectValue(id=2949158, value='Сроки большие (на будущее)')
        partner_y_vmeshivaiutsia = custom_field.SelectValue(id=2949160, value='Партнер(ы) вмешиваются')
        ne_nasha_tsa = custom_field.SelectValue(id=2954260, value='Не наша ЦА (дети, старики)')
        malenkii_gorod_derevnia = custom_field.SelectValue(id=2954262, value='Маленький город-деревня')
        net_nomera_telefona = custom_field.SelectValue(id=2964282, value='Нет номера телефона')
        nekorrektnye_kontakty = custom_field.SelectValue(id=2978098, value='Некорректные контакты')
        peredan_v_investproekt = custom_field.SelectValue(id=2978760, value='Передан в ИнвестПроект')
        bazy_peredan_v = custom_field.SelectValue(id=2979597, value='Базы (Передан в отдел Баз)')
        iskal_drugoe_printsipialno = custom_field.SelectValue(id=2980966, value='Искал другое (принципиально)')
        v_etot_gorod = custom_field.SelectValue(id=2982210, value='В этот город не продаем')
        uzhe_ne_aktualno = custom_field.SelectValue(id=2982212, value='Уже не актуально')
    prichina_otkola_old = custom_field.SelectCustomField("Причина откола (old)", field_id=1278377, enums=PRICHINA_OTKOLA_OLD_ENUMS)

    class STATUS_OTKOLA_OLD_ENUMS:
        kontakt = custom_field.SelectValue(id=2940613, value='Контакт')
        pogruzhen = custom_field.SelectValue(id=2940621, value='Погружен')
        idet_na_vstrechu = custom_field.SelectValue(id=2940629, value='Идет на встречу')
        prinial_reshenie = custom_field.SelectValue(id=2940633, value='Принял решение')
        nekvalifitsirovannyi = custom_field.SelectValue(id=2954040, value='НЕквалифицированный')
        nedostuchalis = custom_field.SelectValue(id=2978762, value='НЕдостучались')
        pokupaet = custom_field.SelectValue(id=2979468, value='Покупает')
        presale = custom_field.SelectValue(id=2981902, value='PreSale')
    status_otkola_old = custom_field.SelectCustomField("Статус откола (old)", field_id=1278781, enums=STATUS_OTKOLA_OLD_ENUMS)
    data_otkola = custom_field.DateCustomField("Дата откола", field_id=1278783)

    class RESURS_ENUMS:
        openbiz_guru = custom_field.SelectValue(id=2943041, value='openbiz.guru')
        prconsult_bz = custom_field.SelectValue(id=2943043, value='prconsult.bz')
        prconsult_in = custom_field.SelectValue(id=2943045, value='prconsult.in')
        prfranshiza_ru = custom_field.SelectValue(id=2943047, value='prfranshiza.ru')
        fr_yastaff = custom_field.SelectValue(id=2943049, value='fr.yastaff')
        email_rassylka = custom_field.SelectValue(id=2948018, value='Еmail рассылка')
        lend_konkurenty = custom_field.SelectValue(id=2950762, value='Ленд конкуренты')
        franshiza_po_gruzchikam = custom_field.SelectValue(id=2952078, value='франшиза-по-грузчикам')
        vebinar = custom_field.SelectValue(id=2952994, value='вебинар')
        yasnow_biz = custom_field.SelectValue(id=2954698, value='yasnow.biz')
        fr_yastaff_plan = custom_field.SelectValue(id=2958218, value='fr.yastaff/plan')
        gk_pr_ru = custom_field.SelectValue(id=2958814, value='gk-pr.ru')
        topfranshizalending = custom_field.SelectValue(id=2958898, value='ТопФраншизаЛендинг')
        podpisinapochtakh = custom_field.SelectValue(id=2959580, value='ПодписиНаПочтах')
        fr_yastaff_cashback = custom_field.SelectValue(id=2965313, value='fr.yastaff/cashback')
        fr_yastaff_akcija = custom_field.SelectValue(id=2967269, value='fr.yastaff/akcija')
        fr_yastaff_black_friday = custom_field.SelectValue(id=2968345, value='fr.yastaff/black-friday')
        fr_yastaff_plantwo = custom_field.SelectValue(id=2978080, value='fr.yastaff/plan2')
        fr_yastaff_black_fridaytwo = custom_field.SelectValue(id=2980372, value='fr.yastaff/black-friday2')
        fr_yastaff_offer = custom_field.SelectValue(id=2982950, value='fr.yastaff/offer')
        fr_yastaff_franshiza = custom_field.SelectValue(id=2982956, value='fr.yastaff/franshiza')
        fr_yastaff_franchise = custom_field.SelectValue(id=2982958, value='fr.yastaff/franchise')
        fr_yastaff_beboss = custom_field.SelectValue(id=2982960, value='fr.yastaff/beboss')
        fr_yastaff_bebosstwo = custom_field.SelectValue(id=2983436, value='fr.yastaff/beboss2')
        businesspartner_ru = custom_field.SelectValue(id=2983888, value='Businesspartner.ru')
        portal = custom_field.SelectValue(id=2984168, value='Портал')
        tilda = custom_field.SelectValue(id=2984226, value='Тильда')
        neizvestno = custom_field.SelectValue(id=2984538, value='неизвестно')
        fr_yastaff_kzn = custom_field.SelectValue(id=2984552, value='fr.yastaff/kzn')
        fr_yastaff_franshizatwo = custom_field.SelectValue(id=2984554, value='fr.yastaff/franshiza2')
        fr_yastaff_franchisetwo = custom_field.SelectValue(id=2984556, value='fr.yastaff/franchise2')
        fr_yastaff_offertwo = custom_field.SelectValue(id=2984558, value='fr.yastaff/offer2')
        fr_yastaff_kzntwo = custom_field.SelectValue(id=2984560, value='fr.yastaff/kzn2')
        fr_yastaff_business = custom_field.SelectValue(id=2984738, value='fr.yastaff/business')
        fr_yastaff_businesstwo = custom_field.SelectValue(id=2984740, value='fr.yastaff/business2')
        fr_yastaff_franchiseua = custom_field.SelectValue(id=2985472, value='fr.yastaff/franchiseua')
        fr_yastaff_franchiseuatwo = custom_field.SelectValue(id=2985474, value='fr.yastaff/franchiseua2')
        fr_yastaff_kp = custom_field.SelectValue(id=2986454, value='fr.yastaff/kp')
        fr_yastaff_franchbiz = custom_field.SelectValue(id=2986634, value='fr.yastaff/franchbiz')
        fr_yastaff_franchbiztwo = custom_field.SelectValue(id=2986636, value='fr.yastaff/franchbiz2')
        franshizanew = custom_field.SelectValue(id=2986796, value='franshizanew')
        franshiza_yastaff_ru = custom_field.SelectValue(id=2987196, value='franshiza.yastaff.ru')
        franshiza_yastaff_ru_a = custom_field.SelectValue(id=2987198, value='franshiza.yastaff.ru/a')
        franch_yastaff_ru = custom_field.SelectValue(id=2987200, value='franch.yastaff.ru')
        franch_yastaff_ru_a = custom_field.SelectValue(id=2987202, value='franch.yastaff.ru/a')
        sevencr_yastaff_ru = custom_field.SelectValue(id=2987204, value='7cr.yastaff.ru')
        den_s_denisom_oneseven_iyulya = custom_field.SelectValue(id=2987206, value='den-s-denisom-17-iyulya')
        longrid = custom_field.SelectValue(id=2987480, value='Лонгрид')
        fr_yastaff_kz = custom_field.SelectValue(id=2988832, value='fr.yastaff/kz')
        fr_yastaff_kztwo = custom_field.SelectValue(id=2988834, value='fr.yastaff/kz2')
        email_franshizapr_ru = custom_field.SelectValue(id=2988898, value='email.franshizapr.ru')
        reshanov_com = custom_field.SelectValue(id=2989076, value='Reshanov.com')
        priamoi_zvonok = custom_field.SelectValue(id=2989078, value='Прямой звонок')
        pismo_na_pochtu = custom_field.SelectValue(id=2989080, value='Письмо на почту')
        cs_yastaff_ru = custom_field.SelectValue(id=2989090, value='cs.yastaff.ru')
        book_reshanov_com = custom_field.SelectValue(id=2990192, value='book.reshanov.com')
        kviz = custom_field.SelectValue(id=2992078, value='Квиз')
        franchise_yastaff_ru_offer = custom_field.SelectValue(id=2992084, value='franchise.yastaff.ru/offer')
        vebinar = custom_field.SelectValue(id=2992160, value='Вебинар')
        franshiza_yastaff_ru_main = custom_field.SelectValue(id=2995978, value='franshiza.yastaff.ru/main')
        franchise_yastaff_ru = custom_field.SelectValue(id=2997638, value='franchise.yastaff.ru')
        markviz = custom_field.SelectValue(id=2997826, value='Марквиз')
        pismo_s_predlozheniem = custom_field.SelectValue(id=2997952, value='Письмо с предложением 1 урока')
        chatbot = custom_field.SelectValue(id=2999306, value='ЧатБОТ')
        avtovoronka = custom_field.SelectValue(id=2999716, value='Автоворонка')
        vystavka = custom_field.SelectValue(id=3007448, value='выставка')
        vklidforma = custom_field.SelectValue(id=3007776, value='ВКлидформа')
        nash_instagramm = custom_field.SelectValue(id=3007920, value='Наш инстаграмм')
        https_franshizapr_ru = custom_field.SelectValue(id=3009018, value='https://franshizapr.ru/')
        whatsapp = custom_field.SelectValue(id=3009296, value='whatsapp')
        fblidforma = custom_field.SelectValue(id=3009402, value='FBлидформа')
        franshiza_yastaff_ru_fedzakaz = custom_field.SelectValue(id=3009414, value='franshiza.yastaff.ru/fedzakaz')
        baza_interes_franshiza = custom_field.SelectValue(id=3010094, value='База_интерес_франшиза')
        imabase_onezerozerozero = custom_field.SelectValue(id=3010432, value='imabase_1000')
        franshiza_yastaff_ru_partner = custom_field.SelectValue(id=3010814, value='franshiza.yastaff.ru/partner')
        franshiza_yastaff_ru_new_outsource = custom_field.SelectValue(id=3010816, value='franshiza.yastaff.ru/new_outsource')
        franshizapersonala_ru = custom_field.SelectValue(id=3011606, value='franshizapersonala.ru')
        https_franchisepr_ru = custom_field.SelectValue(id=3011878, value='https://franchisepr.ru/')
        https_franchisepr_ru_outsource = custom_field.SelectValue(id=3011880, value='https://franchisepr.ru/outsource')
        quiz_yastaff_ru = custom_field.SelectValue(id=3011882, value='quiz.yastaff.ru')
        https_franshiza_yastaff_ru_partner_new = custom_field.SelectValue(id=3012122, value='https://franshiza.yastaff.ru/partner_new')
        insta_eva = custom_field.SelectValue(id=3012210, value='insta_eva')
        https_franshiza_yastaff_ru_partner_promo = custom_field.SelectValue(id=3012276, value='https://franshiza.yastaff.ru/partner_promo')
        https_franchisepr_ru_fedzakaz = custom_field.SelectValue(id=3012278, value='https://franchisepr.ru/fedzakaz')
        http_finplan_franshizapersonala_ru = custom_field.SelectValue(id=3012280, value='http://finplan.franshizapersonala.ru')
        https_franchisepr_ru_finplan = custom_field.SelectValue(id=3012282, value='https://franchisepr.ru/finplan')
        https_franshiza_yastaff_ru_finplan = custom_field.SelectValue(id=3012284, value='https://franshiza.yastaff.ru/finplan')
        prozvon_robotom = custom_field.SelectValue(id=3012460, value='прозвон роботом')
        https_franshiza_yastaff_ru_biz = custom_field.SelectValue(id=3012474, value='https://franshiza.yastaff.ru/biz')
        https_franshizapersonala_ru_franshiza = custom_field.SelectValue(id=3012498, value='https://franshizapersonala.ru/franshiza')
        franshizapersonala_ru_franshiza = custom_field.SelectValue(id=3012528, value='franshizapersonala.ru/franshiza')
        http_franshizapersonala_ru_franshiza = custom_field.SelectValue(id=3012544, value='http://franshizapersonala.ru/franshiza')
        https_fivelessons_reshanov_com = custom_field.SelectValue(id=3012610, value='https://5lessons.reshanov.com')
        telegram = custom_field.SelectValue(id=3012618, value='telegram')
        forum_twozerotwoone = custom_field.SelectValue(id=3012784, value='Форум 2021')
        https_franshiza_yastaff_ru_invest = custom_field.SelectValue(id=3012836, value='https://franshiza.yastaff.ru/invest')
        https_email_franshizapr_ru_black_friday_twozerotwoone = custom_field.SelectValue(id=3012840, value='https://email.franshizapr.ru/black_friday_2021')
        https_franchisepr_ru_blacktwozerotwoone = custom_field.SelectValue(id=3012858, value='https://franchisepr.ru/black2021')
        https_franchisepr_ru_invest = custom_field.SelectValue(id=3012860, value='https://franchisepr.ru/invest')
        rekomendatsiia_ot_partniora = custom_field.SelectValue(id=3012904, value='Рекомендация от партнёра')
        youtube = custom_field.SelectValue(id=3013014, value='youtube')
        https_franchisepr_ru_webinars = custom_field.SelectValue(id=3013036, value='https://franchisepr.ru/webinars')
        https_quiz_franchisepr_ru = custom_field.SelectValue(id=3013064, value='https://quiz.franchisepr.ru')
        https_franchisepr_ru_rukovodstvo_po_vyboru_franshizy = custom_field.SelectValue(id=3013260, value='https://franchisepr.ru/rukovodstvo_po_vyboru_franshizy')
        https_franchisepr_ru_offertwoone = custom_field.SelectValue(id=3013262, value='https://franchisepr.ru/offer21')
        https_franshiza_yastaff_ru_webinar = custom_field.SelectValue(id=3013422, value='https://franshiza.yastaff.ru/webinar')
        https_franchisepr_ru_agent = custom_field.SelectValue(id=3013424, value='https://franchisepr.ru/agent')
        https_oddjob_ru = custom_field.SelectValue(id=3013538, value='https://oddjob.ru/')
        samozaniatye_rf = custom_field.SelectValue(id=3013676, value='самозанятые.рф')
        https_franshiza_yastaff_ru_rost = custom_field.SelectValue(id=3015032, value='https://franshiza.yastaff.ru/rost')
        https_franchisepr_turbo_site = custom_field.SelectValue(id=3015076, value='https://franchisepr.turbo.site')
        https_franchisepr_ru_partner_agent = custom_field.SelectValue(id=3015136, value='https://franchisepr.ru/partner-agent')
        hr = custom_field.SelectValue(id=3015172, value='HR')
        https_franshiza_yastaff_ru_fplan = custom_field.SelectValue(id=3015412, value='https://franshiza.yastaff.ru/fplan')
        https_franchisepr_ru_threethreefiveavto = custom_field.SelectValue(id=3015452, value='https://franchisepr.ru/335avto')
        https_franshiza_yastaff_ru_online_ekskurs_krizis = custom_field.SelectValue(id=3015456, value='https://franshiza.yastaff.ru/online-ekskurs-krizis')
        aktsiia = custom_field.SelectValue(id=3015534, value='Акция')
        vk_senler = custom_field.SelectValue(id=3015574, value='VK_senler')
        biotomic = custom_field.SelectValue(id=3015824, value='biotomic')
        fineducation = custom_field.SelectValue(id=3015826, value='FinEducation')
        work_on = custom_field.SelectValue(id=3015828, value='WORK ON')
        freelead = custom_field.SelectValue(id=3015830, value='freelead')
        wa_baza_two = custom_field.SelectValue(id=3015832, value='WA_Baza_2')
        https_franshiza_yastaff_ru_business = custom_field.SelectValue(id=3015946, value='https://franshiza.yastaff.ru/business')
        priamoe_obrashchenie = custom_field.SelectValue(id=3016048, value='прямое обращение')
        vakansiia = custom_field.SelectValue(id=3016068, value='Вакансия')
        https_franshiza_yastaff_ru_fiveprichin = custom_field.SelectValue(id=3016138, value='https://franshiza.yastaff.ru/5prichin')
    resurs = custom_field.SelectCustomField("Ресурс", field_id=1279825, enums=RESURS_ENUMS)

    class MUSOR_NE_TROGAEM_ENUMS:
        zaiavka = custom_field.SelectValue(id=2943061, value='Заявка')
        kbkh = custom_field.SelectValue(id=2943063, value='КБХ')
        onlain_konsultant = custom_field.SelectValue(id=2943065, value='Онлайн-консультант')
        priamoi_zvonok = custom_field.SelectValue(id=2943067, value='Прямой звонок')
    musor_ne_trogaem = custom_field.SelectCustomField("Мусор (не трогаем)", field_id=1279829, enums=MUSOR_NE_TROGAEM_ENUMS)

    class ZANIATOST_ENUMS:
        onezerozero = custom_field.SelectValue(id=2943965, value='100%')
        parallelno_diversifikator = custom_field.SelectValue(id=2943967, value='Параллельно (диверсификатор)')
    zaniatost = custom_field.SelectCustomField("Занятость", field_id=1280257, enums=ZANIATOST_ENUMS)
    data_prodazhi = custom_field.DateCustomField("Дата продажи", field_id=1280863)

    class AKTSIIA_ENUMS:
        stazhirovka = custom_field.SelectValue(id=2949716, value='Стажировка')
        roialti = custom_field.SelectValue(id=2949718, value='Роялти')
        zhilety = custom_field.SelectValue(id=2949720, value='Жилеты')
        crm_s_personalom = custom_field.SelectValue(id=2952060, value='CRM с персоналом')
        video = custom_field.SelectValue(id=2952062, value='Видео')
        stazhirovka_sneg = custom_field.SelectValue(id=2953946, value='Стажировка/Снег')
        sneg = custom_field.SelectValue(id=2953948, value='Снег')
        nastroika_rk = custom_field.SelectValue(id=2954688, value='Настройка РК')
        nastroika_rk = custom_field.SelectValue(id=2954690, value='Настройка РК + бюджет')
        stazhirovka_one = custom_field.SelectValue(id=2954692, value='Стажировка + 1 день с ДР')
        one_den_s = custom_field.SelectValue(id=2954694, value='1 день с ДР')
        stazhirovka_sneg_nastroika_rk = custom_field.SelectValue(id=2954706, value='Стажировка/Снег/Настройка РК + бюджет')
        sneg_sms = custom_field.SelectValue(id=2957222, value='Снег/Смс')
        sneg_mk_sait_sms = custom_field.SelectValue(id=2957224, value='Снег/МК/Сайт/Смс')
        mk_video = custom_field.SelectValue(id=2957722, value='МК/Видео')
        ipad = custom_field.SelectValue(id=2966022, value='iPad')
        tendery = custom_field.SelectValue(id=2978112, value='Тендеры')
        bez_aktsii = custom_field.SelectValue(id=2978124, value='Без акций')
        call_tsentr = custom_field.SelectValue(id=2986494, value='Call-Центр')
        call_tsentr_stazhirovka = custom_field.SelectValue(id=2986496, value='Call-центр+стажировка')
        konsultatsiia_s_top_menedzherom = custom_field.SelectValue(id=2986498, value='Консультация с Топ-менеджером')
        konsultatsiia_s_topom_sneg = custom_field.SelectValue(id=2986500, value='Консультация с Топом+снег')
        chernaia_piatnitsa = custom_field.SelectValue(id=2991438, value='Черная пятница')
        sneg_avito = custom_field.SelectValue(id=2992148, value='Снег/Авито')
        avito = custom_field.SelectValue(id=2996078, value='Авито')
        agent = custom_field.SelectValue(id=3013006, value='Агент')
        podbor_sotrudnika = custom_field.SelectValue(id=3015288, value='Подбор сотрудника')
    aktsiia = custom_field.SelectCustomField("Акция", field_id=1281416, enums=AKTSIIA_ENUMS)

    class ANKETA_ENUMS:
        da = custom_field.SelectValue(id=2952460, value='Да')
        net = custom_field.SelectValue(id=2952462, value='Нет')
        da_gugl = custom_field.SelectValue(id=2952506, value='Да гугл')
    anketa = custom_field.SelectCustomField("Анкета", field_id=1282316, enums=ANKETA_ENUMS)
    ref = custom_field.UrlCustomField("ref", field_id=1282698)

    class CHISLENNOST_NASELENIIA_GORODA_ENUMS:
        do_twozerozero_k = custom_field.SelectValue(id=2954230, value='до 200 к')
        twozerozero_fivezerozero_k = custom_field.SelectValue(id=2954232, value='200-500 к')
        fivezerozero_onezerozerozero_k = custom_field.SelectValue(id=2954234, value='500-1000 к')
        bolee_milliona = custom_field.SelectValue(id=2954236, value='более миллиона')
    chislennost_naseleniia_goroda = custom_field.SelectCustomField("Численность населения города", field_id=1283106, enums=CHISLENNOST_NASELENIIA_GORODA_ENUMS)

    class VOVLECHENNOST_ENUMS:
        tolko_uznal = custom_field.SelectValue(id=2954242, value='Только узнал')
        slyshal = custom_field.SelectValue(id=2954244, value='Слышал')
        davno_sledit = custom_field.SelectValue(id=2978104, value='Давно следит')
        po_rekomendatsii = custom_field.SelectValue(id=2980106, value='По рекомендации')
    vovlechennost = custom_field.SelectCustomField("Вовлеченность", field_id=1283108, enums=VOVLECHENNOST_ENUMS)
    imia = custom_field.TextCustomField("Имя", field_id=1284096)
    telefon = custom_field.TextCustomField("Телефон", field_id=1284578)
    e_mail = custom_field.TextCustomField("E-mail", field_id=1284580)

    class SROCHNO_ENUMS:
        ochen = custom_field.SelectValue(id=2957298, value='Очень')
        ne_ochen = custom_field.SelectValue(id=2957300, value='Не очень')
    srochno = custom_field.SelectCustomField("Срочно?", field_id=1284588, enums=SROCHNO_ENUMS)
    nomer_pisma = custom_field.TextCustomField("Номер письма", field_id=1284652)
    placement = custom_field.TextCustomField("Placement", field_id=1284668)
    istochnik_trafika = custom_field.BaseCustomField("Источник трафика", field_id=1290580, code="UTM_SOURCE")
    traffic_type = custom_field.BaseCustomField("traffic type", field_id=1290582, code="UTM_MEDIUM")
    nazvanie_reklamnoi_kampanii = custom_field.BaseCustomField("Название рекламной кампании", field_id=1290584, code="UTM_CAMPAIGN")
    kliuchevoe_slovo_kampanii = custom_field.BaseCustomField("Ключевое слово кампании", field_id=1290586, code="UTM_TERM")

    class PONIMANIE_GIR_ENUMS:
        ne_ponimaet = custom_field.SelectValue(id=2978106, value='Не понимает')
        ponimaet = custom_field.SelectValue(id=2978108, value='Понимает')
    ponimanie_gir = custom_field.SelectCustomField("Понимание ГиР", field_id=1293134, enums=PONIMANIE_GIR_ENUMS)
    utm_content = custom_field.TextCustomField("utm_content", field_id=1294036)

    class PRINIMAET_RESHENIE_ENUMS:
        samostoiatelno = custom_field.SelectValue(id=2980110, value='Самостоятельно')
        partner_semia = custom_field.SelectValue(id=2980112, value='Партнер/семья')
    prinimaet_reshenie = custom_field.SelectCustomField("Принимает решение", field_id=1294320, enums=PRINIMAET_RESHENIE_ENUMS)

    class SFERA_ENUMS:
        autsorsing_personala_kadrovoe_agentstvo = custom_field.SelectValue(id=2980114, value='Аутсорсинг персонала/кадровое агентство')
        smezhnaia = custom_field.SelectValue(id=2980116, value='Смежная')
        drugaia = custom_field.SelectValue(id=2980118, value='Другая')
    sfera = custom_field.SelectCustomField("Сфера", field_id=1294322, enums=SFERA_ENUMS)

    class ZAPOLNIL_FORMU_ENUMS:
        da = custom_field.SelectValue(id=2981958, value='Да')
        net = custom_field.SelectValue(id=2981960, value='Нет')
    zapolnil_formu = custom_field.SelectCustomField("Заполнил форму?", field_id=1295662, enums=ZAPOLNIL_FORMU_ENUMS)

    class KONKURENTY_ENUMS:
        rbr = custom_field.SelectValue(id=2982012, value='РБР')
        gs = custom_field.SelectValue(id=2982014, value='ГС')
        rbr_gs = custom_field.SelectValue(id=2982016, value='РБР+ГС')
        net = custom_field.SelectValue(id=2982018, value='нет')
        drugie = custom_field.SelectValue(id=3010966, value='другие')
    konkurenty = custom_field.SelectCustomField("Конкуренты", field_id=1295690, enums=KONKURENTY_ENUMS)
    pervoe_kasanie_two = custom_field.DateCustomField("Первое касание (2)", field_id=1296664)

    class ZVONOK_CHEKERA_ENUMS:
        one_zvonok = custom_field.SelectValue(id=2983296, value='1 звонок')
        two_zvonka = custom_field.SelectValue(id=2983298, value='2 звонка')
        three_zvonka = custom_field.SelectValue(id=2983300, value='3 звонка')
        four_zvonka = custom_field.SelectValue(id=2983302, value='4 звонка')
    zvonok_chekera = custom_field.SelectCustomField("Звонок чекера", field_id=1296666, enums=ZVONOK_CHEKERA_ENUMS)
    rassrochka = custom_field.CheckboxCustomField("Рассрочка", field_id=1296668)
    moneyback = custom_field.CheckboxCustomField("Moneyback", field_id=1296670)
    gorod = custom_field.TextCustomField("Город", field_id=1296672)

    class STATUS_OTKOLA_OLD_TWOZEROTWOONE_ENUMS:
        pervichnyi_kontakt = custom_field.SelectValue(id=2983890, value='Первичный контакт')
        proshel_chekera = custom_field.SelectValue(id=2983892, value='Прошел чекера')
        sostoialsia_kontakt = custom_field.SelectValue(id=2983894, value='Состоялся контакт')
        lid_tselevoi = custom_field.SelectValue(id=2983896, value='Лид целевой')
        vziato_obiazatelstvo_po = custom_field.SelectValue(id=2983898, value='Взято обязательство по анкете')
        anketa_prishla = custom_field.SelectValue(id=2983900, value='Анкета пришла')
        naznacheno_sobesedovanie_s = custom_field.SelectValue(id=2983902, value='Назначено собеседование с руководителем')
        popytka_kontakta_nd = custom_field.SelectValue(id=2987604, value='Попытка контакта (НД)')
        provedeno_sobesedovanie_s = custom_field.SelectValue(id=2987606, value='Проведено собеседование с рук-м')
        zhdem_rekvizity = custom_field.SelectValue(id=2987608, value='Ждем реквизиты')
        zhdem_soglasovaniia_dogovora = custom_field.SelectValue(id=2987610, value='Ждем согласования договора')
        zhdem_skan_dogovora = custom_field.SelectValue(id=2987612, value='Ждем скан договора')
        zhdem_kesh = custom_field.SelectValue(id=2987614, value='Ждем кэш')
        zakryt_na_blok = custom_field.SelectValue(id=3003780, value='Закрыт на блок бабло')
        uspeshno_realizovano = custom_field.SelectValue(id=3006928, value='Успешно реализовано')
        proveden_blok_bablo = custom_field.SelectValue(id=3011092, value='Проведен блок бабло')
    status_otkola_old_twozerotwoone = custom_field.SelectCustomField("Статус откола (old 2021)", field_id=1296910, enums=STATUS_OTKOLA_OLD_TWOZEROTWOONE_ENUMS)

    class PRICHINA_OTKOLA_ENUMS:
        nekorrektnye_kontakty = custom_field.SelectValue(id=2983904, value='Некорректные контакты')
        nevozmozhno_ustanovit_kontakt = custom_field.SelectValue(id=2983906, value='Невозможно установить контакт')
        perestal_brat_trubku_sbrasyvaet = custom_field.SelectValue(id=2983908, value='Перестал брать трубку/сбрасывает')
        v_etot_gorod = custom_field.SelectValue(id=2983910, value='В этот город не продаем')
        iskal_drugoe_printsipialno = custom_field.SelectValue(id=2983912, value='Искал другое (принципиально)')
        net_deneg = custom_field.SelectValue(id=2983916, value='Нет денег')
        malenkii_gorod_derevnia = custom_field.SelectValue(id=2983918, value='Маленький город-деревня')
        sroki_bolshie_na = custom_field.SelectValue(id=2983920, value='Сроки большие (на будущее)')
        peredumal_brat_franshizu = custom_field.SelectValue(id=2983926, value='Передумал брать франшизу в принципе')
        kupil_franshizu_v = custom_field.SelectValue(id=2983932, value='Купил франшизу в другой сфере')
        redpoint_ne_nasha = custom_field.SelectValue(id=2983936, value='Redpoint (не наша ЦА)')
        ne_doveriaet = custom_field.SelectValue(id=2983938, value='Не доверяет')
        chp = custom_field.SelectValue(id=2983940, value='ЧП!')
        kupil_franshizu_rbr_gs_analog = custom_field.SelectValue(id=2983942, value='Купил франшизу РБР/ГС/аналог')
        ne_verit_chto = custom_field.SelectValue(id=2990774, value='Не верит, что у него этот бизнес пойдет')
        menedzher_ne_vyiavil_ne = custom_field.SelectValue(id=2990776, value='Менеджер не выявил/не указал')
        ne_ubedil_v = custom_field.SelectValue(id=3002928, value='Не убедил в ценности франшизы')
        koronavirus = custom_field.SelectValue(id=3003902, value='Коронавирус')
        ishchet_rabotu = custom_field.SelectValue(id=3006608, value='Ищет работу')
        otkol_s_manibeka = custom_field.SelectValue(id=3006930, value='Откол с манибека')
        ne_iskal_franshizu = custom_field.SelectValue(id=3015104, value='не искал франшизу')
        v_poiskakh_raboty = custom_field.SelectValue(id=3015448, value='В поисках работы')
    prichina_otkola = custom_field.SelectCustomField("Причина откола", field_id=1296912, enums=PRICHINA_OTKOLA_ENUMS)
    zvonkov_chekera = custom_field.NumericCustomField("Звонков чекера", field_id=1296914)
    status_chekera = custom_field.TextCustomField("Статус чекера", field_id=1296916)
    utm_hueisment = custom_field.TextCustomField("utm_hueisment", field_id=1298458)
    qone = custom_field.TextCustomField("q1", field_id=1299102)
    qtwo = custom_field.TextCustomField("q2", field_id=1299104)
    qthree = custom_field.TextCustomField("q3", field_id=1299106)
    qfour = custom_field.TextCustomField("q4", field_id=1299108)
    qfive = custom_field.TextCustomField("q5", field_id=1299110)
    qsix = custom_field.TextCustomField("q6", field_id=1299112)
    qthreea = custom_field.TextCustomField("q3a", field_id=1299114)
    qfoura = custom_field.TextCustomField("q4a", field_id=1299116)
    qfivea = custom_field.TextCustomField("q5a", field_id=1299118)
    qm = custom_field.TextCustomField("qm", field_id=1299120)
    instrument_one = custom_field.TextCustomField("Инструмент (1)", field_id=1299160)
    tip_trafika = custom_field.BaseCustomField("Тип трафика", field_id=1299436, code="UTM_MEDIUM")
    data_prikhoda_zaiavki_one_old = custom_field.DateCustomField("Дата прихода заявки (1) old", field_id=1299644)
    roistat_url = custom_field.TextAreaCustomField("ROISTAT_URL", field_id=1300234)
    tranid = custom_field.TextAreaCustomField("TRANID", field_id=1300236)
    formid = custom_field.TextAreaCustomField("FORMID", field_id=1300238)
    referer = custom_field.TextAreaCustomField("REFERER", field_id=1300240)
    pohne = custom_field.TextAreaCustomField("POHNE", field_id=1300254)
    source_checker = custom_field.TextAreaCustomField("SOURCE_CHECKER", field_id=1300284)
    data_prikhoda_zaiavki_two_old = custom_field.DateCustomField("Дата прихода заявки (2) old", field_id=1300536)

    class TIP_TRAFFIKA_TWO_ENUMS:
        iandeks_direkt = custom_field.SelectValue(id=2988846, value='Яндекс Директ')
        google_adwords = custom_field.SelectValue(id=2988848, value='Google Adwords')
        beboss = custom_field.SelectValue(id=2988850, value='Beboss')
        topfranchise_ru = custom_field.SelectValue(id=2988852, value='topfranchise.ru')
        franshiza_ru = custom_field.SelectValue(id=2988854, value='Franshiza.ru')
        email_rassylka = custom_field.SelectValue(id=2988882, value='Email рассылка')
        yastaff = custom_field.SelectValue(id=2988886, value='yastaff')
        organika = custom_field.SelectValue(id=2988892, value='Органика')
        bzzone_ru = custom_field.SelectValue(id=2988896, value='BzZone.ru')
        reklama_socmedia = custom_field.SelectValue(id=2989064, value='Реклама SocMedia')
        profranshizu_ru = custom_field.SelectValue(id=2989074, value='profranshizu.ru')
        to_biz_ru = custom_field.SelectValue(id=2989088, value='to-biz.ru')
        russtartup = custom_field.SelectValue(id=2989266, value='russtartup')
        business_poisk_com = custom_field.SelectValue(id=2989268, value='business-poisk.com')
        money_maker_factory = custom_field.SelectValue(id=2989662, value='Money Maker Factory')
        bizreiting = custom_field.SelectValue(id=2989664, value='Бизрейтинг')
        franch_biz = custom_field.SelectValue(id=2989666, value='Franch.biz')
        franshiza_info = custom_field.SelectValue(id=2989668, value='franshiza-info')
        businesspartner_ru = custom_field.SelectValue(id=2989670, value='businesspartner.ru')
        club_franshiz = custom_field.SelectValue(id=2989672, value='club-franshiz')
        franchise_ua = custom_field.SelectValue(id=2989674, value='Franchise.ua')
        franshiza_top_ru = custom_field.SelectValue(id=2989676, value='franshiza-top.ru')
        vygodnyi_vklad_rf = custom_field.SelectValue(id=2989678, value='выгодный-вклад. рф')
        ktovdele = custom_field.SelectValue(id=2989680, value='ktovdele')
        zaiavka_s_investitsii = custom_field.SelectValue(id=2989682, value='Заявка с инвестиций')
        youtube = custom_field.SelectValue(id=2989684, value='YouTube')
        bizoomie = custom_field.SelectValue(id=2989686, value='bizoomie')
        hiterbober = custom_field.SelectValue(id=2989688, value='hiterbober')
        zachestnyibiznes = custom_field.SelectValue(id=2989690, value='zachestnyibiznes')
        target_vk = custom_field.SelectValue(id=2989692, value='таргет VK')
        bisnesideya_ru = custom_field.SelectValue(id=2989694, value='bisnesideya.ru')
        biztorg_ru = custom_field.SelectValue(id=2989696, value='biztorg.ru')
        deloshop = custom_field.SelectValue(id=2989698, value='deloshop')
        franchay_ru = custom_field.SelectValue(id=2989700, value='franchay.ru')
        myfranch = custom_field.SelectValue(id=2989702, value='myfranch')
        bisplatform = custom_field.SelectValue(id=2989704, value='bisplatform')
        reshanov_com = custom_field.SelectValue(id=2989706, value='Reshanov.com')
        biznes_prost_ru = custom_field.SelectValue(id=2989708, value='Biznes-Prost.ru')
        smi = custom_field.SelectValue(id=2989780, value='СМИ')
        franshizas_ru = custom_field.SelectValue(id=2990208, value='franshizas.ru')
        alterainvest = custom_field.SelectValue(id=2991216, value='АльтераИнвест')
        avito = custom_field.SelectValue(id=2991314, value='Авито')
        businessmens = custom_field.SelectValue(id=2991392, value='businessmens')
        profranch_com = custom_field.SelectValue(id=2991428, value='profranch.com')
        gruppa_bestidea = custom_field.SelectValue(id=2991544, value='Группа Bestidea')
        gruppa_idei_biznesa = custom_field.SelectValue(id=2991546, value='Группа Идеи Бизнеса')
        realybiz = custom_field.SelectValue(id=2992024, value='realybiz')
        smallbusines = custom_field.SelectValue(id=2992152, value='smallbusines')
        biznes_prost_malyi = custom_field.SelectValue(id=2992396, value='Бизнес-прост (малый)')
        abcbiznes_ru = custom_field.SelectValue(id=2993390, value='abcbiznes.ru')
        aktsiia_shattly = custom_field.SelectValue(id=2996982, value='Акция шаттлы')
        fr_mall = custom_field.SelectValue(id=2997476, value='FR.Mall')
        biznesplan_primer_ru = custom_field.SelectValue(id=2998222, value='biznesplan-primer.ru')
        didzhital_baff = custom_field.SelectValue(id=2998562, value='Диджитал Бафф')
        katalog_franshiz_vk = custom_field.SelectValue(id=2999138, value='Каталог франшиз VK')
        newbusiness_su = custom_field.SelectValue(id=2999560, value='newbusiness.su')
        openbusiness = custom_field.SelectValue(id=3000042, value='openbusiness')
        onezerozerozero_ideas = custom_field.SelectValue(id=3000424, value='1000 ideas')
        helpfranchise_ru = custom_field.SelectValue(id=3001492, value='helpfranchise.ru')
        sberbank_franshizy = custom_field.SelectValue(id=3004218, value='Сбербанк Франшизы')
        http_myrouble_ru = custom_field.SelectValue(id=3004264, value='http://myrouble.ru/')
        fbm_ru = custom_field.SelectValue(id=3004266, value='fbm.ru')
        sverdlovskii_fond = custom_field.SelectValue(id=3004364, value='Свердловский фонд')
        franchbook = custom_field.SelectValue(id=3006774, value='franchbook')
        bebosstwo = custom_field.SelectValue(id=3007074, value='Beboss2')
        sabit = custom_field.SelectValue(id=3007080, value='Sabit')
        led_didital = custom_field.SelectValue(id=3007082, value='Led-didital')
        buybrand_ru = custom_field.SelectValue(id=3007574, value='buybrand.ru')
        delosmelo_ru = custom_field.SelectValue(id=3007658, value='delosmelo.ru')
        vk_eva = custom_field.SelectValue(id=3007698, value='VK Ева')
        iula = custom_field.SelectValue(id=3008572, value='Юла')
        instfranshima = custom_field.SelectValue(id=3009100, value='instFranshima')
        franch_city = custom_field.SelectValue(id=3010092, value='franch-city')
        staroverov_pr = custom_field.SelectValue(id=3010466, value='Староверов ПР')
        arkstiks = custom_field.SelectValue(id=3010820, value='Аркстикс')
        digital_buff = custom_field.SelectValue(id=3010846, value='Digital.buff')
        whatsapp = custom_field.SelectValue(id=3011764, value='WhatsApp')
        telegram_kanaly = custom_field.SelectValue(id=3012172, value='Телеграм-каналы')
        target_ann = custom_field.SelectValue(id=3012202, value='Target_Ann')
        tg_posevi = custom_field.SelectValue(id=3012290, value='TG_posevi')
        vk_posevi = custom_field.SelectValue(id=3012292, value='VK_posevi')
        instagram_blogery = custom_field.SelectValue(id=3012308, value='Инстаграм-блогеры')
        vk_posty = custom_field.SelectValue(id=3012310, value='VK посты')
        dzen_posevi = custom_field.SelectValue(id=3012560, value='dzen_posevi')
        biznes_ru = custom_field.SelectValue(id=3012562, value='Бизнес.ру')
        businessesforsale_ru = custom_field.SelectValue(id=3012570, value='businessesforsale.ru')
        partnerkin = custom_field.SelectValue(id=3012602, value='Партнеркин')
        aktsii = custom_field.SelectValue(id=3012642, value='Акции')
        insta_story = custom_field.SelectValue(id=3012768, value='Insta_story')
        budget_city = custom_field.SelectValue(id=3012802, value='budget_city')
        iz_ruk_v = custom_field.SelectValue(id=3012808, value='из рук в руки')
        paket_agent = custom_field.SelectValue(id=3012990, value='Пакет агент')
        vebinar = custom_field.SelectValue(id=3013010, value='Вебинар')
        want_result = custom_field.SelectValue(id=3013060, value='Want Result')
        aglamov = custom_field.SelectValue(id=3013112, value='Aglamov')
        baza_lazerlav = custom_field.SelectValue(id=3013284, value='База Лазерлав')
        tg_bot = custom_field.SelectValue(id=3013380, value='TG_bot')
        kiberone = custom_field.SelectValue(id=3013509, value='KiberOne')
        baza_avito_parcer = custom_field.SelectValue(id=3013590, value='База_Avito_parcer')
        offer_zakrytye = custom_field.SelectValue(id=3013606, value='Оффер_закрытые')
        samozaniatye_rf = custom_field.SelectValue(id=3013678, value='самозанятые.рф')
        abdm = custom_field.SelectValue(id=3013698, value='ABDM')
        vk_fr_yastaff = custom_field.SelectValue(id=3014958, value='ВК fr.yastaff')
        aglamov_ia_direkt = custom_field.SelectValue(id=3015070, value='Aglamov Я.Директ')
        baza_bobiormaster = custom_field.SelectValue(id=3015082, value='База_БобёрМастер')
        baza_khimchistki = custom_field.SelectValue(id=3015086, value='База_Химчистки')
        vk_senler = custom_field.SelectValue(id=3015102, value='VK_senler')
        starye_bazy = custom_field.SelectValue(id=3015120, value='Старые базы')
        tg_kanal_gk = custom_field.SelectValue(id=3015150, value='TG_kanal_GK')
        vc_promo = custom_field.SelectValue(id=3015276, value='VC_promo')
        markway_otzyvy = custom_field.SelectValue(id=3015426, value='Markway_Отзывы')
        transformator = custom_field.SelectValue(id=3015442, value='Трансформатор')
        youtube_posevi = custom_field.SelectValue(id=3015444, value='youtube_posevi')
        prozvon_franchbook = custom_field.SelectValue(id=3015466, value='Прозвон franchbook')
        dzen_target = custom_field.SelectValue(id=3015472, value='Дзен.Таргет')
        zvooc_target = custom_field.SelectValue(id=3015476, value='Zvooc_target')
        headhunter = custom_field.SelectValue(id=3015478, value='HeadHunter')
        akademyey = custom_field.SelectValue(id=3015806, value='AkademyEY')
        yandex_rustem = custom_field.SelectValue(id=3015862, value='yandex_Rustem')
        telegram_channel = custom_field.SelectValue(id=3015866, value='telegram_channel')
        ima_biznes = custom_field.SelectValue(id=3015876, value='ima_Бизнес')
        tg_kanal_gk = custom_field.SelectValue(id=3015880, value='tg_kanal_gk')
        agent_fr_prozvon = custom_field.SelectValue(id=3016130, value='Агент Фр Прозвон')
        zvooc_prozvon = custom_field.SelectValue(id=3016192, value='zvooc_прозвон')
    tip_traffika_two = custom_field.SelectCustomField("Тип траффика (2)", field_id=1300538, enums=TIP_TRAFFIKA_TWO_ENUMS)

    class RESURS_TWO_ENUMS:
        portal = custom_field.SelectValue(id=2988856, value='Портал')
        fr_yastaff = custom_field.SelectValue(id=2988858, value='fr.yastaff')
        franshiza_yastaff_ru = custom_field.SelectValue(id=2988860, value='franshiza.yastaff.ru')
        neizvestno = custom_field.SelectValue(id=2988884, value='неизвестно')
        fr_yastaff_franshiza = custom_field.SelectValue(id=2988888, value='fr.yastaff/franshiza')
        fr_yastaff_plan = custom_field.SelectValue(id=2988890, value='fr.yastaff/plan')
        cs_yastaff_ru = custom_field.SelectValue(id=2988894, value='cs.yastaff.ru')
        email_franshizapr_ru = custom_field.SelectValue(id=2988900, value='email.franshizapr.ru')
        longrid = custom_field.SelectValue(id=2989066, value='Лонгрид')
        reshanov_com = custom_field.SelectValue(id=2989082, value='Reshanov.com')
        priamoi_zvonok = custom_field.SelectValue(id=2989084, value='Прямой звонок')
        pismo_na_pochtu = custom_field.SelectValue(id=2989086, value='Письмо на почту')
        fr_yastaff_ru_business = custom_field.SelectValue(id=2989274, value='fr.yastaff.ru/business')
        kviz = custom_field.SelectValue(id=2995326, value='Квиз')
        franch_yastaff_ru = custom_field.SelectValue(id=2995594, value='franch.yastaff.ru')
        franshiza_yastaff_ru_main = custom_field.SelectValue(id=2996252, value='franshiza.yastaff.ru/main')
        franchise_yastaff_ru = custom_field.SelectValue(id=2996980, value='franchise.yastaff.ru')
        markviz = custom_field.SelectValue(id=2998212, value='Марквиз')
        vystavka = custom_field.SelectValue(id=3007572, value='выставка')
        baza_interes_franshiza = custom_field.SelectValue(id=3010096, value='База_интерес_франшиза')
        fblidforma = custom_field.SelectValue(id=3010112, value='FBлидформа')
        imabase_onezerozerozero = custom_field.SelectValue(id=3010434, value='imabase_1000')
        franshiza_yastaff_ru_fedzakaz = custom_field.SelectValue(id=3010836, value='franshiza.yastaff.ru/fedzakaz')
        franshiza_yastaff_ru_partner = custom_field.SelectValue(id=3010838, value='franshiza.yastaff.ru/partner')
        franshiza_yastaff_ru_new_outsource = custom_field.SelectValue(id=3010840, value='franshiza.yastaff.ru/new_outsource')
        franshizapersonala_ru = custom_field.SelectValue(id=3011608, value='franshizapersonala.ru')
        https_franchisepr_ru = custom_field.SelectValue(id=3011884, value='https://franchisepr.ru/')
        https_franchisepr_ru_outsource = custom_field.SelectValue(id=3011886, value='https://franchisepr.ru/outsource')
        quiz_yastaff_ru = custom_field.SelectValue(id=3011888, value='quiz.yastaff.ru')
        https_franshiza_yastaff_ru_partner_new = custom_field.SelectValue(id=3012124, value='https://franshiza.yastaff.ru/partner_new')
        https_franshiza_yastaff_ru_partner_promo = custom_field.SelectValue(id=3012294, value='https://franshiza.yastaff.ru/partner_promo')
        https_franchisepr_ru_fedzakaz = custom_field.SelectValue(id=3012296, value='https://franchisepr.ru/fedzakaz')
        http_finplan_franshizapersonala_ru = custom_field.SelectValue(id=3012298, value='http://finplan.franshizapersonala.ru')
        https_franchisepr_ru_finplan = custom_field.SelectValue(id=3012300, value='https://franchisepr.ru/finplan')
        https_franshiza_yastaff_ru_finplan = custom_field.SelectValue(id=3012302, value='https://franshiza.yastaff.ru/finplan')
        https_franshiza_yastaff_ru_biz = custom_field.SelectValue(id=3012476, value='https://franshiza.yastaff.ru/biz')
        prozvon_robotom = custom_field.SelectValue(id=3012478, value='Прозвон роботом')
        https_franshizapersonala_ru_franshiza = custom_field.SelectValue(id=3012500, value='https://franshizapersonala.ru/franshiza')
        franshizapersonala_ru_franshiza = custom_field.SelectValue(id=3012530, value='franshizapersonala.ru/franshiza')
        https_fivelessons_reshanov_com = custom_field.SelectValue(id=3012612, value='https://5lessons.reshanov.com')
        forum_twozerotwoone = custom_field.SelectValue(id=3012644, value='Форум 2021')
        nash_instagram = custom_field.SelectValue(id=3012786, value='Наш инстаграм')
        iz_ruk_v = custom_field.SelectValue(id=3012806, value='из рук в руки')
        https_email_franshizapr_ru_black_friday_twozerotwoone = custom_field.SelectValue(id=3012838, value='https://email.franshizapr.ru/black_friday_2021')
        https_franchisepr_ru_blacktwozerotwoone = custom_field.SelectValue(id=3012864, value='https://franchisepr.ru/black2021')
        rekomendatsiia_ot_partniora = custom_field.SelectValue(id=3012906, value='Рекомендация от партнёра')
        rassylka_sms = custom_field.SelectValue(id=3013062, value='Рассылка SMS')
        https_quiz_franchisepr_ru = custom_field.SelectValue(id=3013066, value='https://quiz.franchisepr.ru')
        vebinar = custom_field.SelectValue(id=3013068, value='вебинар')
        telegram = custom_field.SelectValue(id=3013118, value='telegram')
        https_franchisepr_ru_newyeartwozerotwotwo = custom_field.SelectValue(id=3013128, value='https://franchisepr.ru/newyear2022')
        https_franchisepr_ru_agent = custom_field.SelectValue(id=3013172, value='https://franchisepr.ru/agent')
        https_franshiza_yastaff_ru_analyz = custom_field.SelectValue(id=3013526, value='https://franshiza.yastaff.ru/analyz')
        https_oddjob_ru = custom_field.SelectValue(id=3013600, value='https://oddjob.ru/')
        vklidforma = custom_field.SelectValue(id=3013642, value='ВКлидформа')
        samozaniatye_rf = custom_field.SelectValue(id=3013680, value='самозанятые.рф')
        https_franshiza_yastaff_ru_rost = custom_field.SelectValue(id=3015030, value='https://franshiza.yastaff.ru/rost')
        https_franchisepr_turbo_site = custom_field.SelectValue(id=3015078, value='https://franchisepr.turbo.site')
        email_rassylka = custom_field.SelectValue(id=3015122, value='Email рассылка')
        https_franchisepr_ru_partner_agent = custom_field.SelectValue(id=3015138, value='https://franchisepr.ru/partner-agent')
        hr = custom_field.SelectValue(id=3015174, value='HR')
        https_franshiza_yastaff_ru_fplan = custom_field.SelectValue(id=3015414, value='https://franshiza.yastaff.ru/fplan')
        https_franshiza_yastaff_ru_invest = custom_field.SelectValue(id=3015446, value='https://franshiza.yastaff.ru/invest')
        youtube = custom_field.SelectValue(id=3015450, value='youtube')
        https_franchisepr_ru_threethreefiveavto = custom_field.SelectValue(id=3015454, value='https://franchisepr.ru/335avto')
        https_franshiza_yastaff_ru_online_ekskurs_krizis = custom_field.SelectValue(id=3015458, value='https://franshiza.yastaff.ru/online-ekskurs-krizis')
        vakansiia = custom_field.SelectValue(id=3015480, value='Вакансия')
        aktsiia = custom_field.SelectValue(id=3015536, value='Акция')
        vk_senler = custom_field.SelectValue(id=3015576, value='VK_senler')
        https_franshiza_yastaff_ru_business = custom_field.SelectValue(id=3015948, value='https://franshiza.yastaff.ru/business')
        https_franshiza_yastaff_ru_fiveprichin = custom_field.SelectValue(id=3016140, value='https://franshiza.yastaff.ru/5prichin')
    resurs_two = custom_field.SelectCustomField("Ресурс (2)", field_id=1300540, enums=RESURS_TWO_ENUMS)
    roistat_two = custom_field.TextCustomField("roistat (2)", field_id=1300542)
    instrument_two = custom_field.TextCustomField("Инструмент (2)", field_id=1300544)
    utm_source_two = custom_field.TextCustomField("utm_source (2)", field_id=1300546)
    utm_medium_two = custom_field.TextCustomField("utm_medium (2)", field_id=1300548)
    utm_campaign_two = custom_field.TextCustomField("utm_campaign (2)", field_id=1300550)
    utm_term_two = custom_field.TextCustomField("utm_term (2)", field_id=1300552)
    utm_content_two = custom_field.TextCustomField("utm_content (2)", field_id=1300554)
    utm_hueisment_two = custom_field.TextCustomField("utm_hueisment (2)", field_id=1300556)
    traffic_type_two = custom_field.TextCustomField("traffic type (2)", field_id=1300558)
    utm_placement = custom_field.TextAreaCustomField("UTM_PLACEMENT", field_id=1301828)
    vtoroi_shans = custom_field.CheckboxCustomField("Второй шанс", field_id=1302298)

    class MARKETINGOVAIA_AKTSIIA_ENUMS:
        chernaia_piatnitsa_pismo = custom_field.SelectValue(id=2991386, value='Черная пятница (письмо)')
        chernaia_piatnitsa_zaiavka = custom_field.SelectValue(id=2991388, value='Черная пятница (заявка)')
    marketingovaia_aktsiia = custom_field.SelectCustomField("Маркетинговая акция", field_id=1302542, enums=MARKETINGOVAIA_AKTSIIA_ENUMS)
    refer_page = custom_field.TextCustomField("Refer page", field_id=1304288)
    instrument_email = custom_field.TextCustomField("Инструмент email", field_id=1306400)
    bol = custom_field.TextCustomField("Боль", field_id=1307010)
    id_priglasivshego = custom_field.BaseCustomField("ID пригласившего", field_id=1311570, code="REFERRER")

    class SFERA_BIZNESA_ENUMS:
        obshchepit = custom_field.SelectValue(id=3004848, value='Общепит')
        stroitelstvo = custom_field.SelectValue(id=3004850, value='Строительство')
        detskii_biznes = custom_field.SelectValue(id=3004852, value='Детский бизнес')
        razvlecheniia = custom_field.SelectValue(id=3004854, value='Развлечения')
        drugoe = custom_field.SelectValue(id=3004856, value='Другое')
        v_naime = custom_field.SelectValue(id=3004868, value='В найме')
    sfera_biznesa = custom_field.SelectCustomField("Сфера бизнеса", field_id=1311572, enums=SFERA_BIZNESA_ENUMS)
    zakryt_na_blok_bablo_one = custom_field.DateCustomField("Закрыт на блок бабло (1)", field_id=1311952)
    vziato_obiazatelstvo_po_ankete_one = custom_field.DateCustomField("Взято обязательство по анкете (1)", field_id=1311954)
    anketa_prishla_one = custom_field.DateCustomField("Анкета пришла (1)", field_id=1311956)
    naznacheno_sobesedovanie_s_rukovoditelem_one = custom_field.DateCustomField("Назначено собеседование с руководителем (1)", field_id=1311958)
    provedeno_sobesedovanie_s_rukovoditelem_one = custom_field.DateCustomField("Проведено собеседование с руководителем (1)", field_id=1311960)
    zhdiom_rekvizity_one = custom_field.DateCustomField("Ждём реквизиты (1)", field_id=1311962)
    zhdiom_soglasovaniia_dogovora_one = custom_field.DateCustomField("Ждём согласования договора (1)", field_id=1311964)
    zhdiom_skan_dogovora_one = custom_field.DateCustomField("Ждём скан договора (1)", field_id=1311966)
    zhdiom_kesh_one = custom_field.DateCustomField("Ждём кэш (1)", field_id=1311968)
    uspekh_ty_chempion_one = custom_field.DateCustomField("Успех - ты чемпион! (1)", field_id=1311970)
    lts_one = custom_field.TextCustomField("ЛЦ (1)", field_id=1311972)
    lid_tselevoi_one = custom_field.DateCustomField("Лид целевой (1)", field_id=1311974)
    data_poslednego_kontakta = custom_field.DateCustomField("Дата последнего контакта", field_id=1312050)
    tool = custom_field.TextAreaCustomField("TOOL", field_id=1312838, code="TOOL")
    url = custom_field.UrlCustomField("URL", field_id=1312840, code="URL")
    utm_content = custom_field.BaseCustomField("utm_content", field_id=1464345, code="UTM_CONTENT")
    utm_referrer = custom_field.BaseCustomField("utm_referrer", field_id=1464347, code="UTM_REFERRER")
    ym_uid = custom_field.BaseCustomField("_ym_uid", field_id=1464349, code="_YM_UID")
    ym_counter = custom_field.BaseCustomField("_ym_counter", field_id=1464351, code="_YM_COUNTER")
    roistat = custom_field.BaseCustomField("roistat", field_id=1464353, code="ROISTAT")
    openstat_service = custom_field.BaseCustomField("openstat_service", field_id=1464355, code="OPENSTAT_SERVICE")
    openstat_campaign = custom_field.BaseCustomField("openstat_campaign", field_id=1464357, code="OPENSTAT_CAMPAIGN")
    openstat_ad = custom_field.BaseCustomField("openstat_ad", field_id=1464359, code="OPENSTAT_AD")
    openstat_source = custom_field.BaseCustomField("openstat_source", field_id=1464361, code="OPENSTAT_SOURCE")
    _from = custom_field.BaseCustomField("from", field_id=1464363, code="FROM")
    gclientid = custom_field.BaseCustomField("gclientid", field_id=1464365, code="GCLIENTID")
    gclid = custom_field.BaseCustomField("gclid", field_id=1464367, code="GCLID")
    yclid = custom_field.BaseCustomField("yclid", field_id=1464369, code="YCLID")
    fbclid = custom_field.BaseCustomField("fbclid", field_id=1464371, code="FBCLID")
    robot_zvonar_ne_udaliat = custom_field.NumericCustomField("робот звонарь (не удалять)", field_id=1464644)
    traffic_type = custom_field.TextCustomField("traffic_type", field_id=1466568)
    ssylka_zoom = custom_field.UrlCustomField("Ссылка zoom", field_id=1466586, code="ZOOM_LINK")
    ga_utm = custom_field.BaseCustomField("GA UTM", field_id=1466652, code="GA_UTM")
    roistat_visit = custom_field.TextCustomField("roistat_visit", field_id=1466654)
    ad_id = custom_field.TextCustomField("ad_id", field_id=1466702)
    ad_id_two = custom_field.TextCustomField("ad_id (2)", field_id=1466704)

    class SFERA_DEIATELNOSTI_ENUMS:
        stroitelstvo = custom_field.SelectValue(id=3010624, value='Строительство')
        logistika = custom_field.SelectValue(id=3010626, value='Логистика')
        proizvodstva = custom_field.SelectValue(id=3010628, value='Производства')
        sklady = custom_field.SelectValue(id=3010630, value='Склады')
        gos_kompanii = custom_field.SelectValue(id=3010632, value='Гос.компании')
        ivent = custom_field.SelectValue(id=3010634, value='Ивент')
        muving = custom_field.SelectValue(id=3010636, value='Мувинг')
        autsorsing_personala = custom_field.SelectValue(id=3010658, value='Аутсорсинг персонала')
    sfera_deiatelnosti = custom_field.SelectCustomField("Сфера деятельности", field_id=1467802, enums=SFERA_DEIATELNOSTI_ENUMS)

    class PREDSTAVITELSTVA_V_GORODAKH_ENUMS:
        da = custom_field.SelectValue(id=3010642, value='Да')
        net = custom_field.SelectValue(id=3010644, value='Нет')
    predstavitelstva_v_gorodakh = custom_field.RadioButtonCustomField("Представительства в городах", field_id=1467806, enums=PREDSTAVITELSTVA_V_GORODAKH_ENUMS)

    class KOL_VO_VYKHODOV_ENUMS:
        zero_onezero = custom_field.SelectValue(id=3010646, value='0-10')
        oneone_fivezero = custom_field.SelectValue(id=3010648, value='11-50')
        fiveone_onezerozero = custom_field.SelectValue(id=3010650, value='51-100')
        bolee_onezerozero = custom_field.SelectValue(id=3010652, value='более 100')
    kol_vo_vykhodov = custom_field.SelectCustomField("Кол-во выходов", field_id=1467808, enums=KOL_VO_VYKHODOV_ENUMS)
    iur_litso = custom_field.BaseCustomField("Юр.лицо", field_id=1467810)

    class OBSLUZHIVANIE_ENUMS:
        iur_litsa = custom_field.SelectValue(id=3010660, value='Юр.лица')
        fiz_litsa = custom_field.SelectValue(id=3010662, value='Физ.лица')
    obsluzhivanie = custom_field.MultiSelectCustomField("Обслуживание", field_id=1467814, enums=OBSLUZHIVANIE_ENUMS)
    presale = custom_field.TextCustomField("Presale", field_id=1468150)

    class PRICHINA_OTKOLA_AUTSORSERY_ENUMS:
        ne_dozvonitsia = custom_field.SelectValue(id=3011582, value='Не дозвониться')
        ne_ustraivaiut_usloviia = custom_field.SelectValue(id=3011584, value='Не устраивают условия')
        red_point = custom_field.SelectValue(id=3011586, value='RED POINT')
        ne_khochet_razvivat = custom_field.SelectValue(id=3011588, value='Не хочет развивать направление')
        ne_vyiti_na = custom_field.SelectValue(id=3011590, value='Не выйти на ЛПР')
        kompaniia_zakrylas = custom_field.SelectValue(id=3011592, value='Компания закрылась')
        sbrasyvaet = custom_field.SelectValue(id=3011594, value='Сбрасывает')
        ne_kommentiruet_otkaz = custom_field.SelectValue(id=3011596, value='Не комментирует отказ')
        drugoe = custom_field.SelectValue(id=3011598, value='Другое')
        gotov_rabotat_no = custom_field.SelectValue(id=3011604, value='Готов работать, но не устраивают условия')
        net_kontaktnykh_dannykh = custom_field.SelectValue(id=3011610, value='Нет контактных данных')
        net_deneg = custom_field.SelectValue(id=3015410, value='Нет денег')
    prichina_otkola_autsorsery = custom_field.SelectCustomField("Причина откола аутсорсеры", field_id=1468556, enums=PRICHINA_OTKOLA_AUTSORSERY_ENUMS)
    proveden_blok_bablo_one = custom_field.DateCustomField("Проведен блок бабло (1)", field_id=1468674)
    pervoe_kasanie = custom_field.DateTimeCustomField("Первое касание", field_id=1468920)
    pervyi_platezh = custom_field.TextCustomField("Первый платеж", field_id=1468924)

    class RASSROCHKA_ENUMS:
        da = custom_field.SelectValue(id=3011766, value='Да')
        net = custom_field.SelectValue(id=3011768, value='Нет')
    rassrochka = custom_field.SelectCustomField("Рассрочка", field_id=1468926, enums=RASSROCHKA_ENUMS)
    data_rozhdeniia = custom_field.BaseCustomField("Дата рождения", field_id=1468928)
    nomer_dogovora = custom_field.TextCustomField("Номер договора", field_id=1468930)
    kev_ot = custom_field.TextCustomField("КЭВ от:", field_id=1468932)
    grafik_platezhei = custom_field.TextCustomField("---ГРАФИК ПЛАТЕЖЕЙ---", field_id=1468936)
    data_two_go_platezha = custom_field.DateCustomField("Дата 2-го платежа", field_id=1468938)
    summa_two_go_platezha = custom_field.NumericCustomField("Сумма 2-го платежа", field_id=1468940)
    data_three_go_platezha = custom_field.DateCustomField("Дата 3-го платежа", field_id=1468942)
    summa_three_go_platezha = custom_field.NumericCustomField("Сумма 3-го платежа", field_id=1468944)
    data_four_go_platezha = custom_field.DateCustomField("Дата 4-го платежа", field_id=1468946)
    summa_four_go_platezha = custom_field.NumericCustomField("Сумма 4-го платежа", field_id=1468950)
    data_five_go_platezha = custom_field.DateCustomField("Дата 5-го платежа", field_id=1468952)
    summa_five_go_platezha = custom_field.NumericCustomField("Сумма 5-го платежа", field_id=1468954)
    data_six_go_platezha = custom_field.DateCustomField("Дата 6-го платежа", field_id=1468956)
    summa_six_go_platezha = custom_field.NumericCustomField("Сумма 6-го платежа", field_id=1468958)
    data_seven_go_platezha = custom_field.DateCustomField("Дата 7-го платежа", field_id=1468960)
    summa_seven_go_platezha = custom_field.NumericCustomField("Сумма 7-го платежа", field_id=1468962)
    data_eight_go_platezha = custom_field.DateCustomField("Дата 8-го платежа", field_id=1468964)
    summa_eight_go_platezha = custom_field.NumericCustomField("Сумма 8-го платежа", field_id=1468966)
    data_nine_go_platezha = custom_field.DateCustomField("Дата 9-го платежа", field_id=1468968)
    summa_nine_go_platezha = custom_field.NumericCustomField("Сумма 9-го платежа", field_id=1468970)
    data_onezero_go_platezha = custom_field.DateCustomField("Дата 10-го платежа", field_id=1468974)
    summa_onezero_go_platezha = custom_field.NumericCustomField("Сумма 10-го платежа", field_id=1468976)
    obiavlenie = custom_field.TextCustomField("Объявление", field_id=1469144)
    url_obiavleniia = custom_field.UrlCustomField("URL объявления", field_id=1469146)
    lid_poluchen = custom_field.DateTimeCustomField("Лид получен", field_id=1469186)

    class POL_ENUMS:
        muzhskoi = custom_field.SelectValue(id=3011874, value='Мужской')
        zhenskii = custom_field.SelectValue(id=3011876, value='Женский')
    pol = custom_field.SelectCustomField("Пол", field_id=1469188, enums=POL_ENUMS)
    prodazhi_franshiz_etapy = custom_field.TextCustomField("---Продажи франшиз этапы---", field_id=1469190)
    prodazhi_fr_etapy = custom_field.TextCustomField("---Продажи ФР этапы---", field_id=1469192)
    popytka_kontakta = custom_field.DateTimeCustomField("ПОПЫТКА КОНТАКТА", field_id=1469194)
    sostoialsia_kontakt_perezvon = custom_field.DateTimeCustomField("СОСТОЯЛСЯ КОНТАКТ/ПЕРЕЗВОН", field_id=1469196)
    lid_tselevoi = custom_field.DateTimeCustomField("ЛИД ЦЕЛЕВОЙ", field_id=1469198)
    naznachen_kev = custom_field.DateTimeCustomField("НАЗНАЧЕН КЭВ", field_id=1469200)
    kev_podtverzhden = custom_field.DateTimeCustomField("КЭВ ПОДТВЕРЖДЕН", field_id=1469202)
    kev_proveden = custom_field.DateTimeCustomField("КЭВ ПРОВЕДЕН", field_id=1469204)
    vziato_obiazatelstvo_po_ankete = custom_field.DateTimeCustomField("ВЗЯТО ОБЯЗАТЕЛЬСТВО ПО АНКЕТЕ", field_id=1469206)
    anketa_prishla = custom_field.DateTimeCustomField("АНКЕТА ПРИШЛА", field_id=1469208)
    naznacheno_sobesedovanie = custom_field.DateTimeCustomField("НАЗНАЧЕНО СОБЕСЕДОВАНИЕ", field_id=1469210)
    sobesedovanie_provedeno = custom_field.DateTimeCustomField("СОБЕСЕДОВАНИЕ ПРОВЕДЕНО", field_id=1469212)
    zhdem_rekvizity = custom_field.DateTimeCustomField("ЖДЕМ РЕКВИЗИТЫ", field_id=1469214)
    soglasovanie_dogovora = custom_field.DateTimeCustomField("СОГЛАСОВАНИЕ ДОГОВОРА", field_id=1469216)
    zhdem_skan_dogovora = custom_field.DateTimeCustomField("ЖДЕМ СКАН ДОГОВОРА", field_id=1469218)
    zhdem_kesh = custom_field.DateTimeCustomField("ЖДЕМ КЭШ", field_id=1469220)
    uspeshno_realizovano = custom_field.DateTimeCustomField("УСПЕШНО РЕАЛИЗОВАНО", field_id=1469222)
    data_prodazhi_m = custom_field.DateTimeCustomField("Дата продажи М", field_id=1469458)
    pervichnyi_kontakt = custom_field.DateTimeCustomField("ПЕРВИЧНЫЙ КОНТАКТ", field_id=1469460)
    data_prikhoda_zaiavki = custom_field.DateTimeCustomField("Дата прихода заявки", field_id=1469462)

    class STATUS_OTKOLA_ENUMS:
        pervichnyi_kontakt = custom_field.SelectValue(id=3012430, value='ПЕРВИЧНЫЙ КОНТАКТ')
        popytka_kontakta = custom_field.SelectValue(id=3012432, value='ПОПЫТКА КОНТАКТА')
        sostoialsia_kontakt_perezvon = custom_field.SelectValue(id=3012434, value='СОСТОЯЛСЯ КОНТАКТ/ПЕРЕЗВОН')
        lid_tselevoi = custom_field.SelectValue(id=3012436, value='ЛИД ЦЕЛЕВОЙ')
        naznachen_kev = custom_field.SelectValue(id=3012438, value='НАЗНАЧЕН КЭВ')
        kev_podtverzhden = custom_field.SelectValue(id=3012440, value='КЭВ ПОДТВЕРЖДЕН')
        kev_proveden = custom_field.SelectValue(id=3012442, value='КЭВ ПРОВЕДЕН')
        vziato_obiazatelstvo_po = custom_field.SelectValue(id=3012444, value='ВЗЯТО ОБЯЗАТЕЛЬСТВО ПО АНКЕТЕ')
        anketa_prishla = custom_field.SelectValue(id=3012446, value='АНКЕТА ПРИШЛА')
        naznacheno_sobesedovanie = custom_field.SelectValue(id=3012448, value='НАЗНАЧЕНО СОБЕСЕДОВАНИЕ')
        sobesedovanie_provedeno = custom_field.SelectValue(id=3012450, value='СОБЕСЕДОВАНИЕ ПРОВЕДЕНО')
        zhdem_rekvizity = custom_field.SelectValue(id=3012452, value='ЖДЕМ РЕКВИЗИТЫ')
        soglasovanie_dogovora = custom_field.SelectValue(id=3012454, value='СОГЛАСОВАНИЕ ДОГОВОРА')
        zhdem_skan_dogovora = custom_field.SelectValue(id=3012456, value='ЖДЕМ СКАН ДОГОВОРА')
        zhdem_kesh = custom_field.SelectValue(id=3012458, value='ЖДЕМ КЭШ')
        kev_agent_proveden = custom_field.SelectValue(id=3015036, value='КЭВ АГЕНТ ПРОВЕДЕН')
        lid_ne_kvalifitsirovan = custom_field.SelectValue(id=3016064, value='Лид не квалифицирован')
    status_otkola = custom_field.SelectCustomField("Статус откола", field_id=1469602, enums=STATUS_OTKOLA_ENUMS)
    id_polzovatelia = custom_field.TextCustomField("id пользователя", field_id=1469612)
    id_rekl_obiavleniia = custom_field.TextCustomField("id рекл. объявления", field_id=1469614)
    utm_source = custom_field.TextCustomField("UTM_SOURCE", field_id=1469778)
    utm_medium = custom_field.TextCustomField("UTM_MEDIUM", field_id=1469780)
    utm_campaign = custom_field.TextCustomField("UTM_CAMPAIGN", field_id=1469782)
    utm_content = custom_field.TextCustomField("UTM_CONTENT", field_id=1469784)
    utm_term = custom_field.TextCustomField("UTM_TERM", field_id=1469786)
    taplink_utm = custom_field.TextCustomField("---taplink_utm---", field_id=1469788)

    class GREID_ENUMS:
        a = custom_field.SelectValue(id=3012922, value='A+')
        a = custom_field.SelectValue(id=3012924, value='A')
        a = custom_field.SelectValue(id=3012926, value='A-')
        b = custom_field.SelectValue(id=3012928, value='B+')
        b = custom_field.SelectValue(id=3012930, value='B')
        b = custom_field.SelectValue(id=3012932, value='B-')
        c = custom_field.SelectValue(id=3012934, value='C+')
        c = custom_field.SelectValue(id=3012936, value='C')
    greid = custom_field.SelectCustomField("Грейд", field_id=1469920, enums=GREID_ENUMS)
    ball = custom_field.NumericCustomField("Балл", field_id=1469922)
    instrument = custom_field.TextAreaCustomField("Инструмент", field_id=1470082)
    id_klienta_iandeks = custom_field.TextCustomField("ID клиента Яндекс", field_id=1470090)
    google_client_id = custom_field.TextCustomField("Google client ID", field_id=1470092)
    source_phone = custom_field.TextCustomField("Source phone", field_id=1470820)

    class PRICHINA_OTKOLA_AGENT_ENUMS:
        nekorrektnye_dannye = custom_field.SelectValue(id=3014960, value='Некорректные данные')
        nevozmozhno_ustanovit_kontakt = custom_field.SelectValue(id=3014962, value='Невозможно установить контакт')
        net_deneg = custom_field.SelectValue(id=3014964, value='Нет денег')
        otkazali_v_rassrochke = custom_field.SelectValue(id=3014966, value='Отказали в рассрочке')
        sroki_bolshe_three = custom_field.SelectValue(id=3014968, value='Сроки больше 3 мес')
        iskal_rabotu = custom_field.SelectValue(id=3014970, value='Искал работу')
        perestal_brat_trubku = custom_field.SelectValue(id=3014972, value='Перестал брать трубку')
        peredumal_brat_franshizu = custom_field.SelectValue(id=3014974, value='Передумал брать франшизу в принципе')
        ne_khochet_zanimatsia = custom_field.SelectValue(id=3014976, value='Не хочет заниматься рекрутингом')
        vybral_druguiu_franshizu = custom_field.SelectValue(id=3014978, value='Выбрал другую франшизу')
        redpoint = custom_field.SelectValue(id=3015902, value='Redpoint')
        ne_kommentiruet_otkaz = custom_field.SelectValue(id=3015904, value='Не комментирует отказ')
        ne_ubedil_v = custom_field.SelectValue(id=3015906, value='Не убедил в ценности франшизы')
    prichina_otkola_agent = custom_field.SelectCustomField("Причина откола агент", field_id=1470822, enums=PRICHINA_OTKOLA_AGENT_ENUMS)

    class TIP_AGENTA_ENUMS:
        molodezh = custom_field.SelectValue(id=3014980, value='Молодежь')
        potolochnik = custom_field.SelectValue(id=3014982, value='Потолочник')
        predprinimatel_two_popytka = custom_field.SelectValue(id=3014984, value='Предприниматель 2 попытка')
        predprinimatel_rekruter = custom_field.SelectValue(id=3014986, value='Предприниматель-Рекрутер')
        predprinimatel_smezhnik = custom_field.SelectValue(id=3014988, value='Предприниматель-Смежник')
        investor = custom_field.SelectValue(id=3014990, value='Инвестор')
    tip_agenta = custom_field.SelectCustomField("Тип агента", field_id=1470824, enums=TIP_AGENTA_ENUMS)
    minimalnaia_planka_dokhoda = custom_field.NumericCustomField("Минимальная планка дохода", field_id=1470826)
    data_keva = custom_field.DateTimeCustomField("дата КЭВа", field_id=1471538)

    class VEBINAR_CHT_ENUMS:
        zeroseven_zeroseven_twotwo = custom_field.SelectValue(id=3016236, value='07.07.22')
        onefour_zeroseven_twotwo = custom_field.SelectValue(id=3016238, value='14.07.22')
        twoone_zeroseven_twotwo = custom_field.SelectValue(id=3016240, value='21.07.22')
        twoeight_zeroseven_twotwo = custom_field.SelectValue(id=3016242, value='28.07.22')
        zerofour_zeroeight_twotwo = custom_field.SelectValue(id=3016244, value='04.08.22')
        oneone_zeroeight_twotwo = custom_field.SelectValue(id=3016246, value='11.08.22')
        oneeight_zeroeight_twotwo = custom_field.SelectValue(id=3016248, value='18.08.22')
        twofive_zeroeight_twotwo = custom_field.SelectValue(id=3016250, value='25.08.22')
    vebinar_cht = custom_field.MultiSelectCustomField("Вебинар ЧТ", field_id=1471542, enums=VEBINAR_CHT_ENUMS)
    skolko_vebinarov_posetil = custom_field.NumericCustomField("Сколько вебинаров посетил", field_id=1471544)
